update gr.m3u
iptv-org/iptv pull request #1013
Opened 2020-03-02 15:57 UTC by georgoskar

#EXTINF:0 tvg-id="ext" group-title="channels",baraza hd greek music hits
https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv classic 80s-90s  music
https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv music  hits HD  
https://5cc309e93b721.streamlock.net:443/8452/8452/playlist.m3u8

2020-03-03 08:48 UTC, freearhey requested changes

2020-03-03 08:48 UTC, freearhey commented on channels/gr.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="" group-title="Music"Baraza music hits
Lacks a comma before the name of the channel.

2020-03-03 08:53 UTC, georgoskar commented
#EXTINF:0 tvg-id="ext" group-title="channels",baraza hd greek music hits
https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv classic 80s-90s
 music
https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv music  hits HD
https://5cc309e93b721.streamlock.net:443/8452/8452/playlist.m3u8

Στις Τρί, 3 Μαρ 2020 στις 10:48 π.μ., ο/η Aleksandr Statciuk <
notifications@github.com> έγραψε:

> *@freearhey* requested changes on this pull request.
> ------------------------------
>
> In channels/gr.m3u
> <https://github.com/iptv-org/iptv/pull/1013#discussion_r386870823>:
>
> >  #EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="" group-title="Music",Baraza TV Greek Music Hits
>  https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8
> +#EXTINF:-1 <https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8+#EXTINF:-1> tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="" group-title="Music"Baraza music hits
>
> Lacks a comma before the name of the channel.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iptv-org/iptv/pull/1013?email_source=notifications&email_token=ANRE6MJ2QRWC7LB3B7JMHK3RFS74DA5CNFSM4K7XFVM2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXWAZLA#pullrequestreview-367791276>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANRE6MNW7CQBCNU44EYISCTRFS74DANCNFSM4K7XFVMQ>
> .
>

2020-03-03 17:48 UTC, georgoskar commented
#EXTINF:0 tvg-id="ext" group-title="channels",baraza hd greek music hits
https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv classic 80s-90s  music
https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8
#EXTINF:0 tvg-id="ext" group-title="channels",baraza tv music  hits HD  
https://5cc309e93b721.streamlock.net:443/8452/8452/playlist.m3u8

2020-03-03 23:48 UTC, freearhey commented
You need to add the missing comma so I can approve this PR.

2020-03-04 08:01 UTC, georgoskar commented
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
https://i.imgur.com/mW6c2QR.png " group-title="Music",Baraza TV Classic Hits


https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8


#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
https://i.imgur.com/mW6c2QR.png " group-title="Music",Baraza TV Greek Music
Hits


https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8


#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
https://i.imgur.com/mW6c2QR.png " group-title="Music",Baraza TV Music Dance
Hits


https://5cc309e93b721.streamlock.net:443/8452/8452/playlist.m3u8

Στις Τετ, 4 Μαρ 2020 στις 1:48 π.μ., ο/η Aleksandr Statciuk <
notifications@github.com> έγραψε:

> You need to add the missing comma so I can approve this PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iptv-org/iptv/pull/1013?email_source=notifications&email_token=ANRE6MPNYH7N6OTMVBEAJR3RFWJN3A5CNFSM4K7XFVM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENVT2BQ#issuecomment-594230534>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANRE6MJYHEZUEKP7SMBBOQ3RFWJN3ANCNFSM4K7XFVMQ>
> .
>

2020-03-04 08:05 UTC, georgoskar commented
sorry. I hadn't seen it.thanks

Στις Τετ, 4 Μαρ 2020 στις 10:01 π.μ., ο/η barazaradio makis galinos <
tsirlokopio@gmail.com> έγραψε:

> #EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
> https://i.imgur.com/mW6c2QR.png " group-title="Music",Baraza TV Classic
> Hits
>
>
> https://eco.streams.ovh:443/BarazaClassic/BarazaClassic/playlist.m3u8
>
>
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
> https://i.imgur.com/mW6c2QR.png " group-title="Music",Baraza TV Greek
> Music Hits
>
>
> https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8
>
>
> #EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
> https://i.imgur.com/mW6c2QR.png " group-title="Music",Baraza TV Music
> Dance Hits
>
>
> https://5cc309e93b721.streamlock.net:443/8452/8452/playlist.m3u8
>
> Στις Τετ, 4 Μαρ 2020 στις 1:48 π.μ., ο/η Aleksandr Statciuk <
> notifications@github.com> έγραψε:
>
>> You need to add the missing comma so I can approve this PR.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/iptv-org/iptv/pull/1013?email_source=notifications&email_token=ANRE6MPNYH7N6OTMVBEAJR3RFWJN3A5CNFSM4K7XFVM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENVT2BQ#issuecomment-594230534>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANRE6MJYHEZUEKP7SMBBOQ3RFWJN3ANCNFSM4K7XFVMQ>
>> .
>>
>

2020-03-04 10:25 UTC, freearhey commented
As I wrote above, you need to add the missing comma and update your pull request. If you don't know how to do it, watch this video: https://www.youtube.com/watch?v=e41HPOHX9aE.

2020-03-04 21:27 UTC, freearhey approved these changes

2020-03-04 21:27 UTC, merged

2020-03-10 23:57 UTC, georgoskar commented
link correction link baraza greek music hits missing the door 443.
#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Greek" tvg-logo="
https://i.imgur.com/mW6c2QR.png" group-title="Music",Baraza TV Greek Music
Hits https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8

#EXTINF:0 tvg-id="ext" group-title="channels",baraza hd greek music hits
https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8

Στις Τετ, 4 Μαρ 2020 στις 12:25 μ.μ., ο/η Aleksandr Statciuk <
notifications@github.com> έγραψε:

> As I wrote above, you need to add the missing comma and update your pull
> request. If you don't know how to do it, watch this video:
> https://www.youtube.com/watch?v=e41HPOHX9aE.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iptv-org/iptv/pull/1013?email_source=notifications&email_token=ANRE6MLCP3ZN4M7P4JA4FJ3RFYUA7A5CNFSM4K7XFVM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENXHAEA#issuecomment-594440208>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANRE6MIW5OXHQ6URLTG7UW3RFYUA7ANCNFSM4K7XFVMQ>
> .
>

2020-11-18 22:25 UTC, georgoskar commented
Please view this email in an HTML compatible email client.