Update ro.m3u
iptv-org/iptv pull request #11929
Opened 2023-03-27 08:55 UTC by Carlinhos027

Add new channels & repaired links.

Closes #11905 
Closes #10979
Closes #11116
Closes #11123
Closes #11134
Closes #11140 
Closes #11386

2023-03-27 09:44 UTC, BellezaEmporium submitted a review, later dismissed

2023-03-27 15:37 UTC, freearhey requested changes

2023-03-27 15:37 UTC, freearhey commented on streams/ro.m3u
> +http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/albacarolinatv
Offline.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/7253922/227945927-ff0658ed-544a-4731-9334-ef86d0212d8d.png">

2023-03-27 15:37 UTC, freearhey commented on streams/ro.m3u
> +http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/romantv__
Offline.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/7253922/227989836-a590af5e-7180-418b-832b-e5faf2c018ff.png">

2023-03-29 07:27 UTC, BellezaEmporium approved these changes

2023-03-29 11:16 UTC, freearhey approved these changes

2023-03-29 11:16 UTC, merged

2023-03-30 08:53 UTC, trincowski commented
Thanks for the updates!

However, these 3 links are not working for me, they play around 3 seconds and then get stuck. 
- KissTV.ro
- MagicTV.ro
- RockTV.ro

The same thing is happening if I open their official sites. Even in the Browser, the streams get stuck after a couple of seconds...