Update cy.m3u
iptv-org/iptv pull request #12495
Opened 2023-04-22 23:05 UTC by freearhey

Closes #11835

2023-04-23 10:11 UTC, Carlinhos027 requested changes
BRT streams not working.

2023-04-23 10:56 UTC, BellezaEmporium approved these changes, later dismissed

2023-04-23 10:56 UTC, BellezaEmporium commented
@Carlinhos027 Works for me.

2023-04-23 20:16 UTC, freearhey commented
@Carlinhos027 Added the [Geo-blocked] label.

2023-04-23 20:53 UTC, Sphinxroot approved these changes

2023-04-23 21:07 UTC, PopeyeTheSai10r approved these changes

2023-04-24 07:11 UTC, Carlinhos027 approved these changes

2023-04-24 07:12 UTC, merged