Update in.m3u
iptv-org/iptv pull request #12717
Opened 2023-05-06 18:28 UTC by zcraber

Adding KCL TV and Pravasi.

2023-05-07 18:36 UTC, UltraHDR submitted a review, later dismissed

2023-05-07 18:53 UTC, freearhey requested changes

2023-05-07 18:53 UTC, freearhey commented on streams/in.m3u
> +#EXTINF:-1 tvg-id="Pravasi.in",Pravasi (1080p)
```suggestion
#EXTINF:-1 tvg-id="PravasiChannel.in",Pravasi (1080p)
```

2023-05-07 19:04 UTC, freearhey approved these changes

2023-05-08 00:50 UTC, PopeyeTheSai10r approved these changes

2023-05-08 00:51 UTC, merged