Update in.m3u
iptv-org/iptv pull request #12740
Opened 2023-05-08 09:20 UTC by zcraber

Adding Asianet.

2023-05-08 12:42 UTC, PopeyeTheSai10r approved these changes, later dismissed

2023-05-09 03:47 UTC, Alstruit commented on streams/in.m3u
> +#EXTINF:-1 tvg-id="AmritaTV.in",Amrita TV [720p]
```suggestion
#EXTINF:-1 tvg-id="AmritaTV.in",Amrita TV (720p)
```
Formatting.

2023-05-12 02:30 UTC, freearhey requested changes

2023-05-12 02:30 UTC, freearhey commented on streams/in.m3u
> +https://yupptvliveten2.yuppcdn.net/280722/smil:asianetmovies.smil/playlist.m3u8
All links from yuppcdn.net offline.
<img width="583" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/b8e467a8-0f7b-499a-9f30-d2ba2320beb1">

2023-05-13 15:00 UTC, freearhey approved these changes

2023-05-13 15:25 UTC, UltraHDR approved these changes

2023-05-13 15:25 UTC, merged