Update pe.m3u
iptv-org/iptv pull request #12795
Opened 2023-05-12 23:40 UTC by AnonimoJuanPerez

2023-05-13 15:03 UTC, freearhey requested changes

2023-05-13 15:03 UTC, freearhey commented on streams/pe.m3u
> +#EXTINF:-1 tvg-id="Exitosa.pe",Exitosa (720p)
The ID must be the same as in [iptv-org/database](https://github.com/iptv-org/database).

```suggestion
#EXTINF:-1 tvg-id="ExitosaTV.pe",Exitosa (720p)
```

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#stream-description-scheme

2023-05-14 03:07 UTC, freearhey approved these changes

2023-05-14 14:37 UTC, PopeyeTheSai10r approved these changes

2023-05-14 14:37 UTC, merged