Update ir.m3u
iptv-org/iptv pull request #12897
Opened 2023-05-16 17:48 UTC by rasooll

Added a new channel

2023-05-16 19:21 UTC, freearhey requested changes

2023-05-16 19:21 UTC, freearhey commented on streams/ir.m3u
> +#EXTINF:-1 tvg-id="",4U TV (720p)
According to the database, this is the Turkish channel: https://iptv-org.github.io/channel?id=4UTV.tr

```suggestion
#EXTINF:-1 tvg-id="4UTV.tr",4U TV (720p)
```

Should be placed in `streams/tr.m3u`

2023-05-18 23:11 UTC, UltraHDR approved these changes

2023-05-19 20:13 UTC, freearhey approved these changes

2023-05-19 20:13 UTC, merged