Add Kannur Vision & UBL
iptv-org/iptv pull request #12899
Opened 2023-05-16 21:51 UTC by zcraber

2023-05-18 23:12 UTC, UltraHDR submitted a review, later dismissed

2023-05-23 18:39 UTC, freearhey requested changes

2023-05-23 18:39 UTC, freearhey commented on streams/in.m3u
> +http://knr.logichost.in:1935/kannurvision/live/playlist.m3u8
The link doesn't work.

<img width="420" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/96bd401e-da84-4502-853b-3b2e5bf82e29">

2023-05-26 15:56 UTC, freearhey submitted a review, later dismissed

2023-05-27 08:15 UTC, BellezaEmporium approved these changes, later dismissed

2023-05-27 08:16 UTC, BellezaEmporium approved these changes

2023-05-27 17:04 UTC, freearhey approved these changes

2023-05-27 17:04 UTC, merged