Update tr.m3u
iptv-org/iptv pull request #12906
Opened 2023-05-17 11:35 UTC by Emilselimli

Added 
Number 1 Ask
Number 1 Damar
Number 1 Dance

Removed Broken link and closed channel (Ege Turk)

2023-05-18 23:16 UTC, UltraHDR approved these changes, later dismissed

2023-05-19 09:20 UTC, BellezaEmporium requested changes
tvg-logo doesn't go here. You'll need to modify the database in order to make them appear on the final playlist.

2023-05-23 18:26 UTC, freearhey requested changes

2023-05-23 18:26 UTC, freearhey commented on streams/tr.m3u
> +https://b01c02nl.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e2aa8acf44_1/playlist.m3u8
```suggestion
#EXTINF:-1 tvg-id="Number1Ask.tr",Number 1 Ask
https://b01c02nl.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e18f9cea15_1/playlist.m3u8
#EXTINF:-1 tvg-id="Number1Damar.tr",Number 1 DAMAR
https://b01c02nl.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e198784bdc_1/playlist.m3u8
#EXTINF:-1 tvg-id="Number1Dance.tr",Number 1 DANCE
https://b01c02nl.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e2aa8acf44_1/playlist.m3u8
```

2023-05-23 19:22 UTC, BellezaEmporium approved these changes

2023-05-23 19:23 UTC, freearhey approved these changes

2023-05-23 19:23 UTC, merged