Update tr.m3u
iptv-org/iptv pull request #12912
Opened 2023-05-17 12:38 UTC by Emilselimli

The non-working link of channels have been removed and replaced (Streamlock iplink closed)

Add new channels
Number 1 ask
Number 1 damar
Number 1 dance

2023-05-18 22:08 UTC, BellezaEmporium requested changes
tvg-logo doesn't go here. If you need to change the logos, you need to change the [database entries](https://github.com/iptv-org/database] that are linked to this channel.

The rest looks okay to me at first view.

2023-05-20 16:20 UTC, Emilselimli commented
[BellezaEmporium] bugs fixed

2023-05-21 12:37 UTC, BellezaEmporium commented on streams/tr.m3u
> +
```suggestion
```

2023-05-21 12:37 UTC, BellezaEmporium approved these changes, later dismissed
Perfect, LGTM.

2023-05-21 17:24 UTC, UltraHDR commented on streams/tr.m3u
> +https://live.artidijitalmedya.com/artidijital_olaytv/olaytv/chunks.m3u8
Please use playlist.m3u8 instead

2023-05-23 18:31 UTC, freearhey requested changes

2023-05-23 18:31 UTC, freearhey commented on streams/tr.m3u
> +https://live.artidijitalmedya.com/artidijital_olaytv/olaytv/chunks.m3u8
```suggestion
https://live.artidijitalmedya.com/artidijital_olaytv/olaytv/playlist.m3u8
```

2023-05-23 18:34 UTC, freearhey commented on streams/tr.m3u
> +https://b01c02nl.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/u_stream_5c9e2aa8acf44_1/playlist.m3u8
"Number 1" channels are already in your other request #12906

2023-05-29 18:31 UTC, freearhey commented
Closed due to lack of activity.

2023-05-29 18:31 UTC, closed without merging