Update it.m3u
iptv-org/iptv pull request #12921
Opened 2023-05-17 17:53 UTC by trancer1994

Have I done this right? I noticed the Sportitalia channels weren't in the Italy playlist, oir at least weren't in the Sports category. If I duplicated them (laziness on my part), put them in the Sports category instead.

2023-05-18 22:06 UTC, BellezaEmporium requested changes
Several things : 

- Space on line 637 isn't needed.
- Entry lines should correspond to this : 
```
#EXTINF:-1 tvg-id="*insert tvg ID*", *channel name*
```
- Line 645 has a weird string concatenation.

2023-05-21 12:29 UTC, BellezaEmporium commented on streams/it.m3u
> +
```suggestion
```

2023-05-21 12:29 UTC, BellezaEmporium commented on streams/it.m3u
> +#EXTINF:-1 tvg-id="RaiSport2.it" ,Rai Sport 2
```suggestion
#EXTINF:-1 tvg-id="RaiSport2.it",Rai Sport 2
```

2023-05-21 12:29 UTC, BellezaEmporium approved these changes

2023-05-21 18:01 UTC, UltraHDR approved these changes

2023-05-21 18:01 UTC, merged