hotfix over it.m3u
iptv-org/iptv pull request #12953
Opened 2023-05-21 21:15 UTC by BellezaEmporium

2023-05-23 18:49 UTC, freearhey requested changes

2023-05-23 18:49 UTC, freearhey commented on streams/it.m3u
> +https://di-g7ij0rwh.vo.lswcdn.net/sportitalia/simotori.smil/playlist.m3u8
Offline.

<img width="494" alt="image" src="https://github.com/iptv-org/iptv/assets/7253922/717c9284-99c0-43c0-9704-7573f9c1c6c4">

2023-05-23 19:32 UTC, freearhey approved these changes

2023-05-24 08:48 UTC, Carlinhos027 approved these changes

2023-05-24 08:48 UTC, merged

2023-05-24 10:15 UTC, trincowski commented
> Just checked and it seems that stream doesn't exist.

The link appears to be screwed... I cannot test here, but maybe the correct link is https://di-g7ij0rwh.vo.lswcdn.net/sportitalia/simotori.smil/playlist.m3u8 ?