Update ve.m3u
iptv-org/iptv pull request #13404
Opened 2023-06-30 20:32 UTC by interven

Update LatinaTV

2023-06-30 21:22 UTC, BellezaEmporium commented
> Update LatinaTV

Hello and thank you for hosting the channels.
This is not the correct repository for uploading such data. If you see that putting "LatinaTV.ve" in the tvg-id spot doesn't return the logo or sample data, it is because it is missing from the [database](https://github.com/iptv-org/database). Please file an issue or make a pull request adding this channel up.

2023-07-01 11:08 UTC, freearhey requested changes

2023-07-01 11:08 UTC, freearhey commented on streams/ve.m3u
> +#EXTINF:-1 tvg-id="LatinaTV.ve",Latina TV (1080p) tvg-country="VE" tvg-logo="https://latinamedios.com/imagenes/LOGO-LATINA-TV-300-300x200.png"
```suggestion
#EXTINF:-1 tvg-id="LatinaTV.ve",Latina TV (1080p)
```

2023-07-01 11:10 UTC, freearhey approved these changes

2023-07-01 11:12 UTC, BellezaEmporium approved these changes

2023-07-01 11:12 UTC, merged