Update us_roku.m3u
iptv-org/iptv pull request #13506
Opened 2023-07-11 11:03 UTC by ElvisGarces

Include WRA Canal 10

2023-07-11 12:11 UTC, PopeyeTheSai10r approved these changes, later dismissed

2023-07-11 21:51 UTC, freearhey requested changes

2023-07-11 21:51 UTC, freearhey commented on streams/us_roku.m3u
> +#EXTINF:-1 tvg-id="WRAcanal10.com",WRA Canal 10 (1080p)
```suggestion
#EXTINF:-1 tvg-id="",WRA Canal 10 (1080p)
```

https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#stream-description-scheme

2023-07-12 11:56 UTC, UltraHDR approved these changes

2023-07-12 21:40 UTC, freearhey approved these changes

2023-07-12 21:40 UTC, merged