Update cr.m3u
iptv-org/iptv pull request #13539
Opened 2023-07-15 10:48 UTC by Carlinhos027

Closes #12967
Closes #13535

2023-07-15 14:01 UTC, freearhey requested changes

2023-07-15 14:01 UTC, freearhey commented on streams/mx.m3u
> +EXTINF:-1 tvg-id="Foro.mx",Foro TV (1080p)
```suggestion
#EXTINF:-1 tvg-id="Foro.mx",Foro TV (1080p)
```

```sh
/home/runner/work/iptv/iptv/streams/mx.m3u
  64:1  Resource must have a corresponding '#EXTINF' directive  require-info
```

https://github.com/iptv-org/iptv/actions/runs/5562037392/jobs/10160088060?pr=13539

2023-07-15 16:07 UTC, freearhey approved these changes

2023-07-16 12:00 UTC, UltraHDR approved these changes

2023-07-16 12:00 UTC, merged