#13686 Fix Bloomberg HT
iptv-org/iptv pull request #13694
Opened 2023-07-30 20:19 UTC by UltraHDR

2023-07-30 22:25 UTC, freearhey approved these changes, later dismissed

2023-07-30 23:07 UTC, twodragon commented
The channel broadcasts in Turkish. the file you have changed is "us.m3u" please make changes to the "tr.m3u" file

2023-08-01 21:49 UTC, freearhey requested changes

2023-08-01 21:49 UTC, freearhey commented on streams/us.m3u
> +https://ythls.onrender.com/channel/UCApLxl6oYQafxvykuoC2uxQ.m3u8
Please move these links to the `tr.m3u` file.

2023-08-02 18:40 UTC, BellezaEmporium approved these changes

2023-08-02 23:56 UTC, freearhey approved these changes

2023-08-02 23:56 UTC, merged