Update th.m3u
iptv-org/iptv pull request #13962
Opened 2023-08-19 02:30 UTC by Soponwit19997

2023-08-20 05:02 UTC, freearhey approved these changes

2023-08-20 05:05 UTC, freearhey requested changes

2023-08-20 05:05 UTC, freearhey commented on streams/th.m3u
> +https://cdn6.goprimetime.info/feed/202306140918/chpptvhd3/index.m3u8
```suggestion
```

"PPTV HD 36" is on the blocklist due to claims of copyright holders: https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md

2023-08-24 05:29 UTC, freearhey approved these changes

2023-08-24 15:16 UTC, UltraHDR approved these changes

2023-08-24 15:16 UTC, merged