Update id.m3u
iptv-org/iptv pull request #14269
Opened 2023-09-18 14:21 UTC by antosatriani

Update some broken streaming channels

2023-09-22 12:33 UTC, BellezaEmporium reviewed
Are they GEO, by any chance ?

2023-09-22 12:42 UTC, BellezaEmporium requested changes
Tested using an Indonesian proxy, they *do* work but : 

-> the Swiftcontent links only work if you use https
-> The "cgxxxproduction" are in http, weirdly enough.

In order to accept those, you'll need to precise that those links are [Geo-blocked]

2023-09-23 14:49 UTC, antosatriani commented
Ok I see now, Swiftcontent can only be accessed from Indonesian IP network. I will add 'Geo blocked' labels in this playlist

2023-09-23 16:00 UTC, BellezaEmporium approved these changes, later dismissed

2023-09-24 06:54 UTC, Alstruit submitted a review, later dismissed

2023-09-24 07:10 UTC, Alstruit approved these changes

2023-09-24 17:05 UTC, BellezaEmporium approved these changes

2023-09-24 17:05 UTC, merged