Remove all arabic dead links an move working links to ae.m3u
iptv-org/iptv pull request #1445
Opened 2020-05-27 21:29 UTC by Jariix

Dead Links:

http://95.170.215.107/hls/KSA-Sport2-Bakup-M.m3u8	
http://95.170.215.107:80/hls/m3u8/ON-Sport.m3u8	
http://95.170.215.107/hls/Sky-New-A-Backup-M.m3u8	
http://95.170.215.107:80/hls/BBCArabic-Backup-M.m3u8	
http://mn-nl.mncdn.com/alhiwar_live/smil:alhiwar.smil/chunklist_b1264000.m3u8?v&__mn_sid=17174366775755575437	
https://mn-nl.mncdn.com/alhiwar_live/smil:alhiwar.smil/chunklist_b1264000.m3u8	
http://qtv-i.akamaihd.net/hls/live/213233/QTV/s_500330.m3u8	
https://stream.skynewsarabia.com/hls/sna_720.m3u8	
http://live.hibridcdn.net/cnbc/liveabr/cnbc/live1/chunks.m3u8?gmswf=2756198?3292634087	
http://admdn2.cdn.mangomolo.com/nagtv/smil:nagtv.stream.smil/chunklist_b4000000_t64MTA4MHA=.m3u8	
https://stream-05.dc3.dailymotion.com/sec(86G48EQSWKUUFPhHXEV5xihAZ6OwwXGV3CGnvlVY4CA)/dm/3/x74wje5/s/live-3.m3u8	
http://live.hibridcdn.net/cnbc/liveabr/cnbc/live3/chunks.m3u8?gmswf=15392984?787764643	
http://95.170.215.107/hls/m3u8/KSA-Sport1-Bakup.m3u8	
https://bracnet.iptv.jadoodigital.com/live/al_jazeera/playlist.m3u8	
http://103.205.133.42:1935/local/al_arabia_720/index.m3u8

2020-05-27 22:34 UTC, 0x41mmarVM commented
- I notice that a number of these are duplicates. For example you (rightly) removed two links for Al Hiwar

`
http://mn-nl.mncdn.com/alhiwar_live/smil:alhiwar.smil/chunklist_b1264000.m3u8?v&__mn_sid=17174366775755575437
`
`
https://mn-nl.mncdn.com/alhiwar_live/smil:alhiwar.smil/chunklist_b1264000.m3u8
`
But I notice Al Hiwar is also available in uk.m3u with a working link. Not sure what the implication here is, just something I noticed.

- There is also an interesting pattern where some of these are easily fixed by replacing a single quality link with the master playlist.

Example: 
`http://admdn2.cdn.mangomolo.com/nagtv/smil:nagtv.stream.smil/chunklist_b4000000_t64MTA4MHA=.m3u8`
is not working because it's specific for the 4Mb bitrate. Replacing the last part with playlist.m3u8 fixes it:
`http://admdn2.cdn.mangomolo.com/nagtv/smil:nagtv.stream.smil/playlist.m3u8`

- One of the ones you removed seems to be working fine
`https://stream.skynewsarabia.com/hls/sna_720.m3u8`
but it should be changed anyway, the correct (master) link is 
`https://stream.skynewsarabia.com/hls/sna.m3u8`

2020-05-28 01:43 UTC, 0x41mmarVM commented
Most of these are not Emirati channels, they don't belong in ae.m3u

2020-05-28 09:24 UTC, Jariix commented
Where is the Arabic m3u? I want to sort by language.

2020-05-28 09:58 UTC, freearhey requested changes
Please check the marked links again and return the working links back. Also resolve the conflict in the file so we can approve this pull request.

2020-05-28 09:58 UTC, freearhey commented on channels/unsorted.m3u
> -https://edge-1192-ch-gv.filmon.com/live/1778.high.stream/playlist.m3u8
Link works.

2020-05-28 09:58 UTC, freearhey commented on channels/unsorted.m3u
> -https://edge-1192-ch-gv.filmon.com/live/1778.low.stream/playlist.m3u8
Link works.

2020-05-28 09:58 UTC, freearhey commented on channels/unsorted.m3u
> -https://admdn1.cdn.mangomolo.com/adsports1/smil:adsports1.stream.smil/chunklist_b1800000_t64NzIwcA==.m3u8
Link works.

2020-05-28 09:58 UTC, freearhey commented on channels/unsorted.m3u
> -https://admdn5.cdn.mangomolo.com/adsports2/smil:adsports2.stream.smil/chunklist_b1800000_t64NzIwcA==.m3u8
Link works.

2020-05-28 11:31 UTC, 0x41mmarVM commented
@Jariix Sorting by language doesn't require you to move the files, just to define the language in the line. You only need to move them to sort by country. Check the [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md), and the Readme.

2020-05-28 12:13 UTC, Link4K commented on channels/ae.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="" group-title="",Alkuwait Aloula
Already in kw.m3u8

2020-05-28 12:13 UTC, Link4K commented on channels/ae.m3u
> +https://citrusstv.akamaized.net/hls/live/687285/CTV/01.m3u8
Duplicate. Above stream is adaptive

2020-05-28 12:15 UTC, Link4K commented
Most channels are not from the country ae

Please move each channel to the correct country file and avoid duplicated streams.

2020-05-28 12:17 UTC, Link4K requested changes

2020-05-28 12:17 UTC, Link4K commented on channels/ae.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="" tvg-language="Arabic" tvg-logo="" group-title="",RT Arabic HD
In ru.m3u

2020-05-28 12:17 UTC, Link4K commented on channels/ae.m3u
> +#EXTINF:-1 tvg-id="TRTAlArabiya.tr" tvg-name="" tvg-language="Arabic" tvg-logo="" group-title="",TRT Arabic
In the Turkey playlist

2020-05-30 11:43 UTC, Jariix commented
Hello, can you delete this pull request now and I will update the unsorted.m3u in the these days. Thank you in advance.

2020-05-30 15:09 UTC, closed without merging