Updates
iptv-org/iptv pull request #15175
Opened 2023-11-28 14:44 UTC by AntiPontifex

Still updating

2023-11-28 17:20 UTC, freearhey requested changes
To make the error disappear you need to remove these two channels from the playlist.

```sh
/cn_streamlink.m3u
 44    error    "DAZN F1" is on the blocklist due to claims of copyright holders (https://github.com/github/dmca/blob/master/2020/09/2020-09-16-dfl.md)
 88    error    "SKY News" is on the blocklist due to claims of copyright holders (https://github.com/iptv-org/iptv/issues/7[31](https://github.com/iptv-org/iptv/actions/runs/7020426177/job/19100103340?pr=15175#step:6:32)4)
```

https://github.com/iptv-org/iptv/actions/runs/7020426177/job/19100103340?pr=15175

2023-11-28 17:20 UTC, freearhey commented on streams/cn_streamlink.m3u
>  https://sc2022.stream-link.org/tv2306.php?id=e13
```suggestion
```

2023-11-28 17:20 UTC, freearhey commented on streams/cn_streamlink.m3u
>  https://sc2022.stream-link.org/tv2306.php?id=s07
```suggestion
```

2023-11-28 22:59 UTC, Dum4G approved these changes

2023-11-29 10:09 UTC, freearhey approved these changes

2023-11-29 10:09 UTC, merged

2023-11-29 13:34 UTC, AntiPontifex commented
@freearhey Forgot to add: thank you for your help