Add Finnish free-to-air channels and global versions of Yle channels
iptv-org/iptv pull request #15545
Opened 2024-01-12 15:33 UTC by TVKaista

2024-01-13 10:28 UTC, Dum4G requested changes

2024-01-13 10:28 UTC, Dum4G commented on streams/fi.m3u
> +https://live-fi.tvkaista.net/ava/live.m3u8?src=iptvorg
There's no need for source advertisement

2024-01-13 10:28 UTC, Dum4G commented on streams/fi.m3u
> +#EXTINF:-1 tvg-id="YleTV1.fi",YLE TV 1 (720p) [Global version, some programs blocked]
Use [Not 24/7] tag

2024-01-15 07:52 UTC, Dum4G approved these changes

2024-01-15 18:39 UTC, BellezaEmporium approved these changes

2024-01-15 18:39 UTC, merged