Update ve.m3u
iptv-org/iptv pull request #15956
Opened 2024-02-22 16:20 UTC by ElvisGarces

include LGD TV

2024-02-23 16:06 UTC, ElvisGarces reviewed
God

2024-02-23 16:16 UTC, Intervenca reviewed
God

2024-02-24 21:21 UTC, BellezaEmporium requested changes
No ID has been found matching the channel you've indicated. If this is a new channel, please open an addition request onto @iptv-org/database.

![image](https://github.com/iptv-org/iptv/assets/30985701/94ef4c6e-c776-48b2-8acf-c68d354903ae)

2024-02-28 21:09 UTC, Dum4G approved these changes

2024-02-29 19:01 UTC, BellezaEmporium approved these changes

2024-02-29 19:02 UTC, merged