Update in.m3u
iptv-org/iptv pull request #16351
Opened 2024-04-10 16:32 UTC by vishveshjain

Added all sony network channels

2024-04-10 22:02 UTC, Alstruit requested changes
[CONTRIBUTING.md#stream-description-scheme](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#stream-description-scheme)

2024-04-11 10:01 UTC, vishveshjain reviewed
Changes made as per [iptv](https://github.com/iptv-org/iptv/tree/master)
/CONTRIBUTING.md

2024-04-11 11:03 UTC, Alstruit commented on streams/in.m3u
> +#EXTINF:-1 tvg-id="SonyEntertainmentTelevisionAsiaHD.in",	Sony Entertainment Television Asia HD (1080p)
```suggestion
#EXTINF:-1 tvg-id="SonyEntertainmentTelevisionAsiaHD.in",Sony Entertainment Television Asia HD (1080p)
```

2024-04-11 11:03 UTC, Alstruit commented on streams/in.m3u
> +#EXTINF:-1 tvg-id="	SonySAB.in",Sony SAB (1080p)
```suggestion
#EXTINF:-1 tvg-id="SonySAB.in",Sony SAB (1080p)
```

2024-04-11 11:03 UTC, Alstruit approved these changes

2024-04-11 17:24 UTC, Alstruit approved these changes

2024-04-14 00:08 UTC, vishveshjain commented
Hi still waiting for 1 more approval.

2024-04-15 14:38 UTC, BellezaEmporium approved these changes
LGTM.

2024-04-15 14:38 UTC, merged