Update pl_lolokoko.m3u
iptv-org/iptv pull request #16353
Opened 2024-04-11 03:20 UTC by GuyInCanada

2024-04-11 09:19 UTC, Alstruit requested changes

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="ActiveFamily.pl",Active Family (1080p)
```suggestion
#EXTM3U
#EXTINF:-1 tvg-id="ActiveFamily.pl",Active Family (1080p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="BBCCBeebies.pl",BBC CBeebies (576p)
```suggestion
#EXTINF:-1 tvg-id="CBeebies.pl",BBC CBeebies (576p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/ANIMALPLANET.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/FoodNetwork.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="FOX.pl",Fox (720p)
```suggestion
#EXTINF:-1 tvg-id="Fox.pl",Fox (720p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="HISTORY2.pl",H2 (720p)
```suggestion
#EXTINF:-1 tvg-id="History2.pl",H2 (720p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/hgtv.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="MTVPolska.pl",MTV Polska (720p)
```suggestion
#EXTINF:-1 tvg-id="MTV.pl",MTV Polska (720p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="STOPKLATKA.pl",Stopklatka TV (720p)
```suggestion
#EXTINF:-1 tvg-id="StopklatkaTV.pl",Stopklatka TV (720p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +#EXTINF:-1 tvg-id="PULS2.pl",Puls 2 (720p)
```suggestion
#EXTINF:-1 tvg-id="Puls2.pl",Puls 2 (720p)
```

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/Tlc.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/DiscoveryLife.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/EuroSport1.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/Ttv.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 09:19 UTC, Alstruit commented on streams/pl_lolokoko.m3u
> +https://cdn-nvm-london.lolokoko.tv/TvnTurbo.stream/playlist.m3u8
```suggestion
```
DMCA.

2024-04-11 12:25 UTC, Dum4G approved these changes

2024-04-11 12:43 UTC, Alstruit approved these changes

2024-04-11 12:43 UTC, merged

2024-06-15 02:43 UTC, R4IN2007 commented
Here some Poland streams
Fox became FX & TNT became Warner TV

#EXTINF:-4, AMC | (PL)
https://cdn-notpub-london.lolokoko.tv/amc.stream/chunks.m3u8

#EXTINF:-4, Animal Planet | (PL)
https://cdn-notpub-london.lolokoko.tv/animalplanet.stream/chunks.m3u8

#EXTINF:-4, AXN HD | (PL)
https://cdn-notpub-london.lolokoko.tv/axnpolska.stream/chunks.m3u8

#EXTINF:-4, AXN Black | (PL)
https://cdn-notpub-london.lolokoko.tv/axnblack.stream/chunks.m3u8

#EXTINF:-4, AXN White | (PL)
https://cdn-notpub-london.lolokoko.tv/axnwhite.stream/chunks.m3u8

#EXTINF:-4, AXN Spin HD | (PL)
https://cdn-notpub-london.lolokoko.tv/axnspin.stream/chunks.m3u8

#EXTINF:-4, Cartoon Network | (PL)
https://cdn-notpub-london.lolokoko.tv/cartoonnetwork.stream/chunks.m3u8

#EXTINF:-4, CBS Reality | (PL)
https://cdn-notpub-london.lolokoko.tv/cbsreality.stream/chunks.m3u8

#EXTINF:-4, Cinemax | (PL)
https://cdn-notpub-london.lolokoko.tv/cinemax.stream/chunks.m3u8

#EXTINF:-4, Cinemax 2 | (PL)
https://cdn-notpub-london.lolokoko.tv/cinemax2.stream/chunks.m3u8

#EXTINF:-4, Comedy Central | (PL)
https://cdn-notpub-london.lolokoko.tv/comedycentral.stream/chunks.m3u8

#EXTINF:-4, Discovery Channel | (PL)
https://cdn-notpub-london.lolokoko.tv/discoverychannel.stream/chunks.m3u8

#EXTINF:-4, Discovery Historia | (PL)
https://cdn-notpub-london.lolokoko.tv/discoveryhistoria.stream/chunks.m3u8

#EXTINF:-4, Discovery Life | (PL)
https://cdn-notpub-london.lolokoko.tv/discoverylife.stream/chunks.m3u8

#EXTINF:-4, Discovery Science | (PL)
https://cdn-notpub-london.lolokoko.tv/discoveryscience.stream/chunks.m3u8

#EXTINF:-4, DTX | (PL)
https://cdn-notpub-london.lolokoko.tv/dtx.stream/chunks.m3u8

#EXTINF:-4, Disney Channel | (PL)
https://cdn-notpub-london.lolokoko.tv/disneychannel.stream/chunks.m3u8

#EXTINF:-4, Disney Junior | (PL)
https://cdn-notpub-london.lolokoko.tv/disneyjunior.stream/chunks.m3u8

#EXTINF:-4, Disney XD | (PL)
https://cdn-notpub-london.lolokoko.tv/disneyxd.stream/chunks.m3u8

#EXTINF:-4, Food Network | (PL)
https://cdn-notpub-london.lolokoko.tv/foodnetwork.stream/chunks.m3u8

#EXTINF:-4, FX | (PL)
https://cdn-notpub-london.lolokoko.tv/foxpolska.stream/chunks.m3u8

#EXTINF:-4, FX Comedy | (PL)
https://cdn-notpub-london.lolokoko.tv/foxcomedy.stream/chunks.m3u8

#EXTINF:-4, HBO
https://cdn-notpub-london.lolokoko.tv/hbo.stream/chunks.m3u8

#EXTINF:-4, HBO 2
https://cdn-notpub-london.lolokoko.tv/hbo2.stream/chunks.m3u8

#EXTINF:-4, HBO 3
https://cdn-notpub-london.lolokoko.tv/hbo3.stream/chunks.m3u8

#EXTINF:-4, History | (PL)
https://cdn-notpub-london.lolokoko.tv/history.stream/chunks.m3u8

#EXTINF:-4, History 2 | (PL)
https://cdn-notpub-london.lolokoko.tv/history2.stream/chunks.m3u8

#EXTINF:-4, MTV | (PL)
https://cdn-notpub-london.lolokoko.tv/mtvpolska.stream/chunks.m3u8

#EXTINF:-4, Paramount Network | (PL)
https://cdn-notpub-london.lolokoko.tv/paramountchannel.stream/chunks.m3u8

#EXTINF:-4, Sci Fi | (PL)
https://cdn-notpub-london.lolokoko.tv/scifi.stream/chunks.m3u8

#EXTINF:-4, Sundance TV | (PL)
https://cdn-notpub-london.lolokoko.tv/sundance.stream/chunks.m3u8

#EXTINF:-4, TLC | (PL)
https://cdn-notpub-london.lolokoko.tv/tlc.stream/chunks.m3u8

#EXTINF:-4, Warner TV | (PL)
https://cdn-notpub-london.lolokoko.tv/tnt.stream/chunks.m3u8

#EXTINF:-4, Travel Channel | (PL)
https://cdn-notpub-london.lolokoko.tv/travelchannel.stream/chunks.m3u8

2024-06-19 16:22 UTC, trincowski commented
Can you guys load these streams? All of them appear with an Anti-Piracy logo to me. (And the "Oh No No" song.)