More US Updates
iptv-org/iptv pull request #16476
Opened 2024-05-01 12:01 UTC by brokenstream

2024-05-01 15:56 UTC, R4IN2007 commented
Despierta [Geo-blocked]
https://unidfp-nlds136.global.ssl.fastly.net/nlds/univisionnow/challenge28v2/as/live/challenge28v2_hd_pc.m3u8?t1=

Delicioso [Geo-blocked]
https://unidfp-nlds130.global.ssl.fastly.net/nlds/univisionnow/cocina/as/live/cocina_hd_pc.m3u8?t1=

Novelas [Geo-blocked]
https://unidfp-nlds137.global.ssl.fastly.net/nlds/univisionnow/novelasplist/as/live/novelasplist_hd_pc.m3u8?t1=

2024-05-01 20:21 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-celebrityscene/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-celebrityscene/index.m3u8
```
Adaptive

2024-05-01 20:21 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-chefchampion/tracks-v1a1/mono.m3u8
```suggestion
https://bozztv.com/gusa/gusa-chefchampion/mono.m3u8
```
Adaptive

2024-05-01 20:21 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-chefrock/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-chefrock/index.m3u8
```
Adaptive

2024-05-01 20:22 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-classiccinema/tracks-v1a1/mono.m3u8
```suggestion
https://bozztv.com/gusa/gusa-classiccinema/index.m3u8
```
Adaptive

2024-05-01 20:22 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-mwg/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-mwg/index.m3u8
```

2024-05-01 20:22 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsbowling/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsbowling/index.m3u8
```
Adaptive

2024-05-01 20:22 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsboxing/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsboxing/index.m3u8
```
Adaptive

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsmystery/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsmystery/index.m3u8
```
Adaptive

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsclassicmovies/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsclassicmovies/index.m3u8
```

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvs/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvs/index.m3u8
```

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvscomedy/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvscomedy/index.m3u8
```

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsdriveinmovie/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsdriveinmovie/index.m3u8
```

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-TVSFamilyChannel/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-TVSFamilyChannel/index.m3u8
```

2024-05-01 20:23 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/trn01/gusa-TVSFilmNoir/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/trn01/gusa-TVSFilmNoir/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-TVSFlashback/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-TVSFlashback/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsfrontier/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsfrontier/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-hitops/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-hitops/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvshollywoohistory/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvshollywoohistory/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsmusic/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsmusic/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-nostalgia/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-nostalgia/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsNostalgiaMovies/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsNostalgiaMovies/index.m3u8
```

2024-05-01 20:24 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-petparadenetwork/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-petparadenetwork/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-TVSCartoonNetwork/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-TVSCartoonNetwork/ndex.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsgameshow/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsgameshow/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsselect/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsselect/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvssports/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvssports/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvssportsbureau/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvssportsbureau/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-TVStalk/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-TVStalk/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvstallyho/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvstallyho/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tavern/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tavern/index.m3u8
```

2024-05-01 20:25 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvstn/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvstn/index.m3u8
```

2024-05-01 20:26 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvstravel/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvstravel/index.m3u8
```

2024-05-01 20:26 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsturbo/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsturbo/index.m3u8
```

2024-05-01 20:26 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvsvintage/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvsvintage/index.m3u8
```

2024-05-01 20:26 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvswesternmovies/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvswesternmovies/index.m3u8
```

2024-05-01 20:26 UTC, BellezaEmporium commented on streams/us.m3u
> +https://bozztv.com/gusa/gusa-tvswsn/tracks-v1a1/index.m3u8
```suggestion
https://bozztv.com/gusa/gusa-tvswsn/index.m3u8
```

2024-05-01 20:26 UTC, BellezaEmporium requested changes
Please keep the adaptive playlists when possible.

2024-05-02 06:21 UTC, brokenstream commented
All fixed.

2024-05-02 11:24 UTC, BellezaEmporium approved these changes

2024-05-04 00:44 UTC, Sphinxroot approved these changes

2024-05-06 00:00 UTC, Alstruit commented
@ADPNetworkPlus
Please state where you wish to make changes. Or mark as resolved.

2024-05-06 01:31 UTC, Alstruit commented
Closing in favor of #16493 due to no response from conversation.

2024-05-06 01:31 UTC, closed without merging