add franken.plus
iptv-org/iptv pull request #16488
Opened 2024-05-03 14:13 UTC by motherboard1999

2024-05-04 04:49 UTC, PopeyeTheSai10r approved these changes, later dismissed

2024-05-04 12:51 UTC, Alstruit requested changes

2024-05-04 12:51 UTC, Alstruit commented on streams/de.m3u
> +#EXTINF:-1 tvg-id="franken.plus",FrankenPlus (1080p)
Invalid ID

2024-05-18 10:00 UTC, BellezaEmporium commented on streams/de.m3u
> +#EXTINF:-1 tvg-id="franken.plus",FrankenPlus (1080p)
```suggestion
#EXTINF:-1 tvg-id="",FrankenPlus (1080p)
```

2024-05-18 10:00 UTC, BellezaEmporium approved these changes

2024-05-18 13:43 UTC, Alstruit approved these changes

2024-05-18 13:46 UTC, merged