Update mx.m3u
iptv-org/iptv pull request #1701
Opened 2020-08-22 22:26 UTC by Ballzslayer213

Added public channels

2020-08-23 04:32 UTC, AKJK-Internet-Megacorps approved these changes

2020-08-23 11:41 UTC, freearhey requested changes
Please double-check all links in PR. None of the links are working at this time. Tested in VLC and Elmedia Video Player.

2020-08-25 13:35 UTC, freearhey requested changes
Please check the marked link again

2020-08-25 13:35 UTC, freearhey commented on channels/mx.m3u
> +https://5e50264bd6766.streamlock.net:443/canal22/smil:canal22.smil/playlist.m3u8
link no longer works

2020-09-11 13:02 UTC, closed without merging