Update us.m3u
iptv-org/iptv pull request #17045
Opened 2024-07-21 14:23 UTC by ProPontifex

See title

2024-07-22 04:28 UTC, Alstruit submitted a review, later dismissed

2024-07-27 21:46 UTC, Dum4G requested changes

2024-07-27 21:46 UTC, Dum4G commented on streams/us.m3u
> -https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc6us/master.m3u8
works for me

2024-08-03 21:07 UTC, BellezaEmporium commented on streams/us.m3u
> -https://qvc-amd-live.akamaized.net/hls/live/2034113/lsqvc6us/master.m3u8
Can confirm it works for me too.

2024-08-05 11:44 UTC, BellezaEmporium commented on streams/us.m3u
> -https://fl5.moveonjoy.com/MTV_U/index.m3u8
http://fl5.moveonjoy.com/MTV_U/index.m3u8 works

2024-08-08 20:48 UTC, Dum4G commented
@ProPontifex please consider to follow request changes

2024-08-11 05:19 UTC, closed without merging

2024-08-11 18:40 UTC, ProPontifex commented
Why was this closed?

2024-08-11 21:32 UTC, BellezaEmporium commented
Seems like it's linked to what @Dum4G posted.

2024-08-11 22:18 UTC, ProPontifex commented
Um, ok

2024-08-13 17:35 UTC, Dum4G commented
I have nothing against reopening this case but please consider not removing channels that work

2024-08-14 02:08 UTC, ProPontifex commented
Same here, but if I removed the channels they weren't working on my end (in Canada). If you point out specific examples, I'll be glad to reconsider.