Update cn.m3u
iptv-org/iptv pull request #17071
Opened 2024-07-25 02:43 UTC by iotv0815

fill empty tvg-id with channel name

2024-07-27 21:31 UTC, Dum4G requested changes
![image](https://github.com/user-attachments/assets/e4c4b9ef-b89a-46b1-b270-23670dbb7783)
Please make sure tvg-id exist in database [iptv-org.github.io](https://iptv-org.github.io/)

2024-07-28 07:16 UTC, BellezaEmporium commented
AFAIK there's no dashes in a tvg-id.

2024-07-28 07:18 UTC, BellezaEmporium commented
![image](https://github.com/user-attachments/assets/2369f781-bf5f-42f5-b7bb-b4aaae788964)

2024-07-28 07:21 UTC, BellezaEmporium commented on streams/cn.m3u
> +#EXTINF:-1 tvg-id="ZheJiang-Life.cn",浙江民生
Channel is the same than the one below.

Is it the "Minsheng Leisure" channel or the "Life" channel ? (last one being inexistant in the database).

2024-07-28 07:39 UTC, BellezaEmporium commented on streams/cn.m3u
>  https://hw-m-l.cztv.com/channels/lantian/channel05/720p.m3u8
Doesn't exist anymore.

Either https://qiniup-m-l.cztv.com/channels/lantian/channel05/1080p.m3u8 (loop for now)
or https://ali-m-l.cztv.com/channels/lantian/channel05/1080p.m3u8 (loop for now)
or https://ct-m-l.cztv.com/channels/lantian/channel05/1080p.m3u8 (loop for now)

2024-07-28 07:41 UTC, BellezaEmporium commented on streams/cn.m3u
>  https://hw-m-l.cztv.com/channels/lantian/channel008/1080p.m3u8
ZhejiangEducationTechnologyChannel.cn per the image above.

Alt https://qiniup-m-l.cztv.com/channels/lantian/channel008/1080p.m3u8
or https://ct-m-l.cztv.com/channels/lantian/channel008/1080p.m3u8

2024-07-28 07:45 UTC, BellezaEmporium commented on streams/cn.m3u
>  https://hw-m-l.cztv.com/channels/lantian/channel010/1080p.m3u8
Alt https://qiniup-m-l.cztv.com/channels/lantian/channel010/1080p.m3u8
or https://ct-m-l.cztv.com/channels/lantian/channel010/1080p.m3u8

![image](https://github.com/user-attachments/assets/3f361915-2440-4478-87e2-3c3569b4f1b5)

2024-07-28 07:45 UTC, BellezaEmporium commented on streams/cn.m3u
>  https://hw-m-l.cztv.com/channels/lantian/channel07/1080p.m3u8
Alt https://qiniup-m-l.cztv.com/channels/lantian/channel007/1080p.m3u8
or https://ct-m-l.cztv.com/channels/lantian/channel007/1080p.m3u8

![image](https://github.com/user-attachments/assets/91b1a5d0-ac0e-4692-9f73-8a4ad6bed380)

2024-07-30 20:02 UTC, BellezaEmporium commented on streams/cn.m3u
> + https://ct-m-l.cztv.com/channels/lantian/channel007/1080p.m3u8
```suggestion
https://ct-m-l.cztv.com/channels/lantian/channel007/1080p.m3u8
```

2024-07-30 20:03 UTC, BellezaEmporium commented on streams/cn.m3u
>  https://hw-m-l.cztv.com/channels/lantian/channel008/1080p.m3u8
```suggestion
https://qiniup-m-l.cztv.com/channels/lantian/channel008/1080p.m3u8
#EXTINF:-1 tvg-id="ZhejiangChildrensChannel.cn",浙江少儿 (1080p)
https://ct-m-l.cztv.com/channels/lantian/channel008/1080p.m3u8
```

2024-08-30 20:05 UTC, Dum4G commented
Time has come? @BellezaEmporium

2024-08-30 20:08 UTC, BellezaEmporium commented
There's still some work to do but you may approve what's already been done.

2024-08-30 20:25 UTC, Dum4G approved these changes

2024-08-30 20:38 UTC, Alstruit approved these changes

2024-08-30 20:38 UTC, merged