Update sv.m3u
iptv-org/iptv pull request #17089
Opened 2024-07-27 23:29 UTC by KAREEM160504

ACTUALIZACION.

Orbita FM , Se cambio el m3u8

SUGERENCIA.

Agregue Tigo Sports SV.

Espero aprobacion. Gracias y saludos

2024-07-28 07:47 UTC, BellezaEmporium commented on streams/sv.m3u
> +#EXTINF:-1 tvg-id="GSGTV.sv",GSG TV (720p)
```suggestion
#EXTINF:-1 tvg-id="GSGTV.sv",GSG TV (720p)
```

2024-07-28 07:47 UTC, BellezaEmporium commented on streams/sv.m3u
> +#EXTINF:-1 tvg-id="15TigoSports.sv",Tigo Sports TV El Salvador (720p)
```suggestion
#EXTINF:-1 tvg-id="TigoSports.sv",Tigo Sports TV El Salvador (720p) [Geo-blocked]
```

2024-07-28 07:47 UTC, BellezaEmporium commented on streams/sv.m3u
> +https://fl1003.bozztv.com/ssh101/OrbitaFM953/tracks-v1a1/mono.m3u8
```suggestion
https://fl1003.bozztv.com/ssh101/OrbitaFM953/index.m3u8
```

2024-07-28 07:48 UTC, BellezaEmporium approved these changes

2024-07-28 07:54 UTC, BellezaEmporium commented on streams/sv.m3u
> +https://channel03.tigosports.com.sv/out/v1/31f36d52d558475ca18799d8ca5e4b40/index.m3u8
Seems like it needs an account to get access to the channel.

2024-07-28 07:54 UTC, BellezaEmporium approved these changes

2024-07-28 07:54 UTC, BellezaEmporium requested changes
See comments.

2024-07-31 02:15 UTC, R4IN2007 commented
Sirve buen la signal de Tigo Sports nomas que es geo-blockado.
![Screenshot_20240730_200438_Chrome](https://github.com/user-attachments/assets/9aa6bc50-ac24-4cf2-a6f4-764d3197f55b)

2024-07-31 20:06 UTC, BellezaEmporium commented
> Sirve buen la signal de Tigo Sports nomas que es geo-blockado. ![Screenshot_20240730_200438_Chrome](https://private-user-images.githubusercontent.com/83226646/353667101-9aa6bc50-ac24-4cf2-a6f4-764d3197f55b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTY2NzksIm5iZiI6MTcyMjQ1NjM3OSwicGF0aCI6Ii84MzIyNjY0Ni8zNTM2NjcxMDEtOWFhNmJjNTAtYWMyNC00Y2YyLWE2ZjQtNzY0ZDMxOTdmNTViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTJmMzRjMmFiYmIxMWU2Yzg3NmVhYWE2ZDY4YzA2MDk2MTg0OWYyMzBhMzk3NTczNDI2ZTUwYzc5YzRiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvt4bZ50vu3Ie017JjSVmANpJskoa_vCai3EBoX_ojA)

![image](https://github.com/user-attachments/assets/904c756a-94e5-46de-a6b4-922d405684ea)

2024-07-31 20:57 UTC, Dum4G approved these changes

2024-08-01 04:18 UTC, R4IN2007 commented
> > Sirve buen la signal de Tigo Sports nomas que es geo-blockado. ![Screenshot_20240730_200438_Chrome](https://private-user-images.githubusercontent.com/83226646/353667101-9aa6bc50-ac24-4cf2-a6f4-764d3197f55b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTY2NzksIm5iZiI6MTcyMjQ1NjM3OSwicGF0aCI6Ii84MzIyNjY0Ni8zNTM2NjcxMDEtOWFhNmJjNTAtYWMyNC00Y2YyLWE2ZjQtNzY0ZDMxOTdmNTViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTJmMzRjMmFiYmIxMWU2Yzg3NmVhYWE2ZDY4YzA2MDk2MTg0OWYyMzBhMzk3NTczNDI2ZTUwYzc5YzRiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvt4bZ50vu3Ie017JjSVmANpJskoa_vCai3EBoX_ojA)
> 
> ![image](https://private-user-images.githubusercontent.com/30985701/353981285-904c756a-94e5-46de-a6b4-922d405684ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODYxNTQsIm5iZiI6MTcyMjQ4NTg1NCwicGF0aCI6Ii8zMDk4NTcwMS8zNTM5ODEyODUtOTA0Yzc1NmEtOTRlNS00NmRlLWE2YjQtOTIyZDQwNTY4NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA0MTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWY0ZTU3ZDU0ODM0NzIzOGI1ODc2ODZhYjU4MjQxNmIyOTY1ZmFiOTU1YTJmZmMwNTFmZWNhZGIzZTc5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-XRkCiQl4nLPlVA5NYFlA727GihZjClWgdbVVUWUn0)

Works using a ip from El Salvador.

2024-08-01 09:18 UTC, BellezaEmporium commented
> > > Sirve buen la signal de Tigo Sports nomas que es geo-blockado. ![Screenshot_20240730_200438_Chrome](https://private-user-images.githubusercontent.com/83226646/353667101-9aa6bc50-ac24-4cf2-a6f4-764d3197f55b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTY2NzksIm5iZiI6MTcyMjQ1NjM3OSwicGF0aCI6Ii84MzIyNjY0Ni8zNTM2NjcxMDEtOWFhNmJjNTAtYWMyNC00Y2YyLWE2ZjQtNzY0ZDMxOTdmNTViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTJmMzRjMmFiYmIxMWU2Yzg3NmVhYWE2ZDY4YzA2MDk2MTg0OWYyMzBhMzk3NTczNDI2ZTUwYzc5YzRiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvt4bZ50vu3Ie017JjSVmANpJskoa_vCai3EBoX_ojA)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/30985701/353981285-904c756a-94e5-46de-a6b4-922d405684ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODYxNTQsIm5iZiI6MTcyMjQ4NTg1NCwicGF0aCI6Ii8zMDk4NTcwMS8zNTM5ODEyODUtOTA0Yzc1NmEtOTRlNS00NmRlLWE2YjQtOTIyZDQwNTY4NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA0MTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWY0ZTU3ZDU0ODM0NzIzOGI1ODc2ODZhYjU4MjQxNmIyOTY1ZmFiOTU1YTJmZmMwNTFmZWNhZGIzZTc5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-XRkCiQl4nLPlVA5NYFlA727GihZjClWgdbVVUWUn0)
> 
> Works using a ip from El Salvador. https://streamtest.in/logs/https-channel03-tigosports-com-sv-out-v1-31f36d52d558475ca18799d8ca5e4b40-index-m3u8-3ec4b8f3-0871-4e8f-9b41-073ed7937c8f

I've tried too with an IP from El Salvador, got a 403.

2024-08-08 20:50 UTC, Dum4G commented
@KAREEM160504 can you show us a screenshot of working Tigo from VLC player?

2024-08-08 20:51 UTC, BellezaEmporium commented
What @R4IN2007 posted seems to be a good clue that it works, however it's a heavy GEO.

2024-08-14 16:48 UTC, BellezaEmporium approved these changes

2024-08-14 16:49 UTC, merged