Update eg.m3u
iptv-org/iptv pull request #17133
Opened 2024-08-07 09:41 UTC by MohamedAsaad1

2024-08-08 20:18 UTC, Dum4G requested changes

2024-08-08 20:18 UTC, Dum4G commented on streams/eg.m3u
> -https://nogoumtv.nrpstream.com/hls/stream.m3u8
also works for me

2024-08-08 20:18 UTC, Dum4G commented on streams/eg.m3u
> +https://www.dailymotion.com/cdn/live/video/x856hbh.m3u8?sec=9vSsiUOJ8a7kbWMNXFepsHC8OlUumUou8hjpl3rNDWoafrpc5h41D3xPlx1FAO0g&dmTs=564260&dmV1st=34048c79-30a8-4360-a956-3e718b976feb
tokenized

2024-08-10 08:32 UTC, BellezaEmporium commented on streams/eg.m3u
> +https://nogoumtv.nrpstream.com/hls/0/stream.m3u8
Basically avoiding a redirection. If they decide to upgrade their quality, it's better to stay with the adaptive stream.

2024-08-10 08:33 UTC, BellezaEmporium approved these changes

2024-08-10 09:36 UTC, Dum4G approved these changes

2024-08-10 09:36 UTC, merged