Update streams
iptv-org/iptv pull request #17480
Opened 2024-09-12 02:44 UTC by Alstruit

2024-09-13 21:18 UTC, Dum4G requested changes

2024-09-13 21:18 UTC, Dum4G commented on streams/us.m3u
> -https://tgn.bozztv.com/betterlife/betterhealth/betterhealth/index.m3u8
![image](https://github.com/user-attachments/assets/eec678f1-6473-4edf-bdf0-a79ff2d24bb5)

2024-09-13 21:18 UTC, Dum4G commented on streams/us.m3u
> -https://tgn.bozztv.com/betterlife/betternature/betternature/index.m3u8
![image](https://github.com/user-attachments/assets/51442e3b-e432-4a22-ac69-c372dc9b3f34)

2024-09-13 21:18 UTC, Dum4G commented on streams/us.m3u
> -https://tgn.bozztv.com/betterlife/betterlife/betterlife/index.m3u8
![image](https://github.com/user-attachments/assets/9a738b5a-72bf-4d75-abc7-e715b49f2853)

2024-09-13 21:18 UTC, Dum4G commented on streams/us.m3u
> -https://tgn.bozztv.com/lifevision/lifevision/index.m3u8
![image](https://github.com/user-attachments/assets/40b19151-837a-446c-ab28-37a1a8fc6c4c)

2024-09-13 21:18 UTC, Dum4G commented on streams/us.m3u
> -https://ntv2.akamaized.net/hls/live/2013923/NASA-NTV2-HLS/master.m3u8
![image](https://github.com/user-attachments/assets/a2a1c090-e124-49d7-a160-016c781a9ced)
valid

2024-09-13 21:18 UTC, Dum4G commented on streams/xk.m3u
> +https://ub1doy938d.gjirafa.net/live/Gfsqdsr7FewrYClU3ACEGZvCHktt2wse/yt1q1x.m3u8
![image](https://github.com/user-attachments/assets/164a90ef-20a6-454a-bd40-a1f796dbd9ea)

2024-09-14 07:29 UTC, Dum4G approved these changes

2024-09-14 09:30 UTC, BellezaEmporium approved these changes

2024-09-14 09:30 UTC, merged