Update ro.m3u - Moinesti FM
iptv-org/iptv pull request #17797
Opened 2024-10-16 18:20 UTC by StefCoders

webm - icecast stream

(if needed I can get m3u8 link)

2024-10-17 16:09 UTC, StefCoders commented
Changed webm link to m3u8

2024-10-19 09:28 UTC, Dum4G requested changes

2024-10-19 09:28 UTC, Dum4G commented on streams/ro.m3u
> +https://video.moinestifm.ro/hls/moinestifm.m3u8
![image](https://github.com/user-attachments/assets/8e0a3783-39b4-40b6-a582-ed6ada619650)

2024-10-19 10:13 UTC, StefCoders commented
Should be working now, sorry for the mishap.

2024-10-19 11:09 UTC, Dum4G commented on streams/ro.m3u
> +#EXTINF:-1 tvg-id="MoinestiFM.ro" tvg-logo="https://moinestifm.ro/images/logo_color.png",Moinesti FM (720p)
```suggestion
#EXTINF:-1 tvg-id="",Moinesti FM (720p)
```

2024-10-19 11:09 UTC, Dum4G approved these changes

2024-10-19 18:48 UTC, BellezaEmporium approved these changes

2024-10-19 18:48 UTC, merged