Logos for it.m3u
iptv-org/iptv pull request #2207
Opened 2021-03-01 17:20 UTC by YacineBoussoufa

2021-03-01 22:16 UTC, LaneSh4d0w commented
LGTM.

2021-03-02 10:51 UTC, freearhey requested changes
Please remove extra links from PR so that we can approve the rest of the changes.

2021-03-02 10:51 UTC, freearhey commented on channels/it.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="" tvg-country="IT" tvg-language="Italian" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/c/ce/Virgin_Radio_Italy_logo.svg" group-title="",Virgin Radio Italia
All these channels are already on the playlist.

2021-03-02 12:20 UTC, freearhey approved these changes

2021-03-02 12:20 UTC, freearhey approved these changes

2021-03-02 12:20 UTC, merged