Update id.m3u
iptv-org/iptv pull request #2209
Opened 2021-03-02 05:27 UTC by Dzaky05

+ RCTI, MNC TV, and GTV

2021-03-02 10:45 UTC, freearhey requested changes
Please check the marked links again.

2021-03-02 10:45 UTC, freearhey commented on channels/id.m3u
> +https://iptv-ppvhxd1r4.vercel.app/api/vidio?id=778
None of the links work.

2021-03-03 04:53 UTC, Dzaky05 commented on channels/id.m3u
> +https://iptv-ppvhxd1r4.vercel.app/api/vidio?id=778
I was fixed the link.

2021-03-03 09:34 UTC, freearhey approved these changes

2021-03-03 09:34 UTC, merged

2021-03-03 09:34 UTC, freearhey commented
@Dzaky05 Thank you for your help!