Add missing LocalNow channels.
iptv-org/iptv pull request #2511
Opened 2021-04-28 08:33 UTC by heroku-miraheze

2021-04-28 10:55 UTC, freearhey requested changes

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +
Unnecessary blank line.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://buzzr-localnow.amagi.tv/playlist.m3u8
Broken link.
<img width="687" alt="Captura de pantalla 2021-04-28 a las 13 44 27" src="https://user-images.githubusercontent.com/7253922/116391694-28b46000-a828-11eb-8053-3c0cb010a65d.png">

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://linear-130.frequency.stream/dist/localnow/130/bpk-tv/BNC-OTT/default/index.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://livestream.chdrstatic.com/e1bced8988f6a21da2206247c69538b6d4b12898ae8245c3a72f57e21384ccba/localnow/localnowlive/cheddardigital/index.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://1622862207.rsc.cdn77.org/FTF/FTF_SCTE.m3u8
Broken link.
<img width="706" alt="Captura de pantalla 2021-04-28 a las 13 51 14" src="https://user-images.githubusercontent.com/7253922/116392182-ce67cf00-a828-11eb-90c9-8f8455a820e1.png">

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://d39jokgb64z0et.cloudfront.net/dist/localnow/86/hls/master/playlist.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://1840769862.rsc.cdn77.org/FTF/LSN_SCTE.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://livestream.chdrstatic.com/2272f9cc29d3f9e812a3b4cacbd767bf69c95a59434c3f482606a67962a0dd5e/localnow/n12nyLocalNow/news12newyork/primary/index.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://nmxlocalnow.akamaized.net/hls/live/2020471/Live_1/index.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://547f72e6652371c3.mediapackage.us-east-1.amazonaws.com/out/v1/e3e6e29095844c4ba7d887f01e44a5ef/index.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://linear-76.frequency.stream/dist/localnow/76/hls/master/playlist.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://sportsgrid-localnow-us.amagi.tv/playlist.m3u8
Broken link.
<img width="686" alt="Captura de pantalla 2021-04-28 a las 13 54 12" src="https://user-images.githubusercontent.com/7253922/116392533-39190a80-a829-11eb-9049-7fce6a930499.png">

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://venntv-localnow.amagi.tv/index.m3u8
The link is already in the playlist.

2021-04-28 10:55 UTC, freearhey commented on channels/unsorted.m3u
> +https://whistletv-localnow.amagi.tv/playlist.m3u8
Broken link.
<img width="662" alt="Captura de pantalla 2021-04-28 a las 13 55 19" src="https://user-images.githubusercontent.com/7253922/116392674-606fd780-a829-11eb-9d78-897b0d4d1de9.png">

2021-04-28 15:04 UTC, LaneSh4d0w commented on channels/unsorted.m3u
> +https://whistletv-localnow.amagi.tv/playlist.m3u8
Geolocked.

2021-04-28 15:05 UTC, LaneSh4d0w commented on channels/unsorted.m3u
> +https://sportsgrid-localnow-us.amagi.tv/playlist.m3u8
Geolocked.
![image](https://user-images.githubusercontent.com/30985701/116427021-eef15280-a843-11eb-8c5b-72b2dd02e3fd.png)

2021-04-28 15:06 UTC, LaneSh4d0w commented on channels/unsorted.m3u
> +https://1622862207.rsc.cdn77.org/FTF/FTF_SCTE.m3u8
Most certainly geolocked.

![image](https://user-images.githubusercontent.com/30985701/116427104-03cde600-a844-11eb-8b43-91d999b13710.png)

2021-04-28 15:06 UTC, LaneSh4d0w commented on channels/unsorted.m3u
> +https://buzzr-localnow.amagi.tv/playlist.m3u8
Geolocked too.

2021-04-30 20:47 UTC, freearhey commented
Since no changes have been made, I'm closing the PR for now.

2021-04-30 20:47 UTC, closed without merging