Update es.m3u
iptv-org/iptv pull request #2560
Opened 2021-05-02 17:27 UTC by trancer1994

Spain (including Basque Terrotories and Catelonia (if you want to split these up in the future you can do so))

2021-05-03 00:07 UTC, freearhey requested changes
Please remove extra line.

2021-05-03 00:07 UTC, freearhey commented on channels/es.m3u
> +Norway:
Invalid line.

2021-05-03 00:12 UTC, freearhey commented
We divide channels into files based on the list of countries from [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) and that is why only Spain is on the list.

2021-05-07 14:02 UTC, freearhey commented
Closed due to lack of any activity.

2021-05-07 14:02 UTC, closed without merging

2021-05-07 14:10 UTC, trancer1994 commented
It says "This pull request is closed, but the trancer1994:patch-34 branch has unmerged commits". What do I do now?

2021-05-07 16:01 UTC, freearhey commented
@trancer1994 You can leave it as it is. It's not an error, just a notification.