Update mx.m3u
iptv-org/iptv pull request #2629
Opened 2021-05-05 11:21 UTC by trancer1994

2021-05-05 19:02 UTC, freearhey requested changes
Please check the marked link again.

2021-05-05 19:02 UTC, freearhey commented on channels/mx.m3u
> +https://wmaqlive-f.akamaihd.net/i/wmaqb1_1@24420/index_1286_av-p.m3u8?sd=10&rebase=on
The link is broadcasting NBC Chicago, which is American.

2021-05-07 16:22 UTC, freearhey commented
@trancer1994 Just to clarify: should I close your other PRs or do you plan to edit them later?

2021-05-07 16:38 UTC, trancer1994 commented
@Freearhy Feel free to close this one in particular if you want as I might not find any other channels, but leave specifically the ES one open as there's a channel Allegria TV which I suspect may be broadcasting from Spain. Also I'll also be editing some other files later with other channels I find in my text document I have which is basically a text version of the unsorted list from about a few days ago. But now I don't know whether to edit it anymore since someone on another thread has basically called me an asshole and accused me of stealing others' hard work, it's that IPTV-free guy again. The trouble is I believe some of the unsorted channels in my list are the same as was in his, so don't know whether to commit them to the individual countries' files here. I don't want to get accused of stealing stuff.

2021-05-07 20:18 UTC, freearhey commented
@trancer1994 If this guy has any complaints about our playlists and wants us to remove some channels he owns the rights to, he can write [here](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=DMCA&template=--remove-channel.md&title=Remove%3A+xxx) and we will remove them all within one working day.

2021-05-08 12:49 UTC, closed without merging

2021-05-08 17:09 UTC, trancer1994 commented
@Freearhey He doesn't own the rights to any channels. He is that same person who made an issue asking you to remove all the links from his playlists claiming this repo stole a bunch of them. Now he's started commenting on the first pull request I made where I updated the UK list for the first time and calling me an arsehole and saying what a hard-working hore I am.

2021-05-08 19:45 UTC, freearhey commented
@trancer1994 If they bother you, you can just [block or report](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account) them. In this case they will no longer be able to comment on your work.