Added a bunch of Tijuana Locals
iptv-org/iptv pull request #2954
Opened 2021-05-29 16:52 UTC by MapGuy11

2021-05-29 19:46 UTC, themak1985 requested changes
Thanks @MapGuy11 - for future reference, just add the new channels to the bottom of the playlist, the script will automatically alphabetize the list later. Check in streamtest, all failed, all worked in VLC.

I'll leave it up to other reviewers to decide whether or not you should remove the tvg-id and tvg-name fields as there is no epg for those currently.

2021-05-29 20:02 UTC, freearhey approved these changes

2021-05-29 20:08 UTC, freearhey commented
@themak1985 It does not make much difference which `tvg-id` it is if the channel is not yet on [epg/codes.csv](https://github.com/iptv-org/epg/blob/master/codes.csv). 

But if you leave the `tvg-id` field empty, the script will try automatically generate a correct ID based on the channel name.

2021-05-29 21:17 UTC, LaneSh4d0w requested changes

2021-05-29 21:17 UTC, LaneSh4d0w commented on channels/mx.m3u
> +https://streams.the6tv.duckdns.org:2443/locals/SanDiego/xetv-tdt.m3u8
Duplicate.

2021-05-30 10:28 UTC, LaneSh4d0w approved these changes

2021-05-30 21:24 UTC, themak1985 approved these changes

2021-05-30 21:24 UTC, merged