AM : Add channels
iptv-org/iptv pull request #3081
Opened 2021-06-08 19:54 UTC by LaneSh4d0w

Astra streams

2021-06-08 22:08 UTC, Dum4G commented
Shant Premuim is not a Sport channel

2021-06-08 22:08 UTC, Dum4G requested changes

2021-06-08 22:08 UTC, Dum4G commented on channels/am.m3u
> +#EXTINF:-1 tvg-id="ShantPremium.am" tvg-name="Shant Premium" tvg-country="AM" tvg-language="Armenian" tvg-logo="" group-title="Sports",Shant Premium
Shant Premuim is not a Sport channel

2021-06-09 10:50 UTC, freearhey approved these changes

2021-06-09 10:51 UTC, merged