UA : Add channels
iptv-org/iptv pull request #3087
Opened 2021-06-08 21:44 UTC by LaneSh4d0w

Odessa channels / Astra server streams.

2021-06-08 23:23 UTC, freearhey requested changes

2021-06-09 07:23 UTC, LaneSh4d0w commented on channels/ua.m3u
> +http://212.79.122.23:8000/play/a00e/index.m3u8
Ah yes, both American and Russian...

2021-06-09 07:23 UTC, LaneSh4d0w commented on channels/ua.m3u
> +http://212.79.122.23:8000/play/a00u/index.m3u8
Noted, moving.

2021-06-09 10:46 UTC, freearhey approved these changes

2021-06-09 10:47 UTC, merged