Updates - Read Below
iptv-org/iptv pull request #3734
Opened 2021-07-27 22:14 UTC by MapGuy11

1. Change MeTV West (I assume) to MeTV Arizona from (Distributed Antenna System)
2. Add Pennsylvania Cable Network from (BozzTV/TeleupTV)
3. Add Entertainment Studios Channels from (BozzTV/TeleupTV)
4. Add Popular Digital Subchannels from (Distributed Antenna System)
5. Add 2 **NEW** Subchannels in the US _True Real_ and _Defy TV_

2021-07-27 23:42 UTC, Dum4G requested changes

2021-07-27 23:42 UTC, Dum4G commented on channels/us.m3u
> +https://bozztv.com/teleyupp/teleup-pcnhd/playlist.m3u8
Every BozzTV link is Geo-Blocked

2021-07-27 23:42 UTC, Dum4G commented on channels/us.m3u
> +#EXTINF:-1 tvg-id="CARSTV.us" tvg-name="Cars.TV" tvg-country="US" tvg-language="English" tvg-logo="https://zap2it.tmsimg.com/h3/NowShowing/71302/s71302_h3_aa.png" group-title="Entertainment",Cars.TV
Sounds like Auto category

2021-07-27 23:59 UTC, MapGuy11 commented on channels/us.m3u
> +https://bozztv.com/teleyupp/teleup-pcnhd/playlist.m3u8
Will Fix

2021-07-27 23:59 UTC, MapGuy11 commented on channels/us.m3u
> +#EXTINF:-1 tvg-id="CARSTV.us" tvg-name="Cars.TV" tvg-country="US" tvg-language="English" tvg-logo="https://zap2it.tmsimg.com/h3/NowShowing/71302/s71302_h3_aa.png" group-title="Entertainment",Cars.TV
Will Fix

2021-07-28 11:34 UTC, Dum4G commented
I'll check every BozzTV channel for geo-block and resolve merge conflict first. Channels you have added didn't open for me but KTLA5 works just fine

2021-07-28 12:03 UTC, Dum4G commented
@LaneSh4d0w  I'v got an interesting behavior to check. I was able to watch every BozzTV channel with teleyupp in links just fine, but when I tried one with teleyupp1 it started to restrict me. Please check if you can reproduce the same

2021-07-28 15:36 UTC, LaneSh4d0w commented
> @LaneSh4d0w  I'v got an interesting behavior to check. I was able to watch every BozzTV channel with teleyupp in links just fine, but when I tried one with teleyupp1 it started to restrict me everywhere. Please check if you can reproduce the same
> 
> UPD: as expected, it was a temporal block

I'll check that, had a few things to do.

2021-07-28 19:19 UTC, LaneSh4d0w commented
Links I've checked worked fine, no blockage whatsoever @Dum4G

2021-07-28 19:21 UTC, Dum4G commented
> Links I've checked worked fine, no blockage whatsoever @Dum4G

Even if you try teleyupp1 link and then smth else?

2021-07-28 19:24 UTC, LaneSh4d0w commented
Yes, actually i've alternated between teleyupp and teleyupp1, then going back to teleyupp, and all of them worked fine (tested C-Span, Fox 7 and Freeform)

2021-07-28 19:25 UTC, Dum4G commented
I'm removing geo-blocked tag then

2021-07-28 21:50 UTC, Dum4G commented
At this point I don't want to expirement with Github Desktop merge implementation. I'll do all of the changes from here in a new PR

2021-07-28 21:50 UTC, closed without merging