WW: Issuing marathon
iptv-org/iptv pull request #3832
Opened 2021-08-01 07:38 UTC by Dum4G

Closes https://github.com/iptv-org/iptv/issues/3830

2021-08-01 12:12 UTC, tilfizyawn requested changes

2021-08-01 12:12 UTC, tilfizyawn commented on channels/uk.m3u
> +#EXTINF:-1 tvg-id="ITV.uk" tvg-name="ITV" tvg-country="UK" tvg-language="" tvg-logo="https://i.imgur.com/SsgOgRF.png" group-title="",ITV
```suggestion
#EXTINF:-1 tvg-id="ITV.uk" tvg-name="ITV" tvg-country="UK" tvg-language="English" tvg-logo="https://i.imgur.com/SsgOgRF.png" group-title="",ITV
```

2021-08-01 12:12 UTC, tilfizyawn commented on channels/uk.m3u
> +http://sportportal1.akamaized.net/hls/live/702647/itvlive/ITV4PORTAL2/master.m3u8
```suggestion
https://sportportal1.akamaized.net/hls/live/702647/itvlive/ITV4PORTAL2/master.m3u8
```

2021-08-01 23:51 UTC, LaneSh4d0w commented
Persiana Classic : http://51.210.199.26/hls/stream.m3u8

2021-08-01 23:54 UTC, LaneSh4d0w commented
http://51.210.199.28/hls/stream.m3u8 Indicates 4 HD... sounds like another channel of the 4Turk category.

2021-08-02 23:50 UTC, Sphinxroot approved these changes

2021-08-02 23:51 UTC, merged

2021-08-03 07:38 UTC, MH140000 commented
http://51.210.199.30/hls/stream.m3u8 sepanj tv
http://51.210.199.1/hls/stream.m3u8 Toheed tv

2021-08-03 07:40 UTC, MH140000 commented
I would be happy to help if you would like help with Iranian streams.