Update fr.m3u
iptv-org/iptv pull request #3872
Opened 2021-08-03 08:21 UTC by MH140000

add and change sum group-title channels

2021-08-03 11:29 UTC, Dum4G commented
https://github.com/iptv-org/iptv/blob/master/.readme/supported-categories.md

Please check our list of supported categories

2021-08-03 13:54 UTC, LaneSh4d0w requested changes, later dismissed

2021-08-03 13:54 UTC, LaneSh4d0w commented on channels/fr.m3u
> +#EXTINF:-1 tvg-id="PersianaVarzesh.fr" tvg-name="Persiana Varzesh" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Sport",Persiana Varzesh
```suggestion
#EXTINF:-1 tvg-id="PersianaVarzesh.fr" tvg-name="Persiana Varzesh" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Sports",Persiana Varzesh
```

2021-08-03 13:54 UTC, LaneSh4d0w commented on channels/fr.m3u
> +#EXTINF:-1 tvg-id="PokerTV.fr" tvg-name="Poker TV" tvg-country="IR" tvg-language="" tvg-logo="https://i.imgur.com/l5fZQ3V.png" group-title="Sport",Poker TV [Not 24/7]
```suggestion
#EXTINF:-1 tvg-id="PokerTV.fr" tvg-name="Poker TV" tvg-country="IR" tvg-language="" tvg-logo="https://i.imgur.com/l5fZQ3V.png" group-title="Sports",Poker TV [Not 24/7]
```

Mitigated idea... for me playing Poker sounds like a hobby.

2021-08-04 23:31 UTC, Dum4G approved these changes

2021-08-04 23:32 UTC, merged