Update jp.m3u
iptv-org/iptv pull request #3903
Opened 2021-08-04 11:02 UTC by tonyt89

2021-08-04 11:34 UTC, LaneSh4d0w commented on channels/jp.m3u
> +#EXTINF:-1 tvg-id="BSTVTokyo.jp" tvg-name="BS TV Tokyo" tvg-country="JP" tvg-language="Japanese" tvg-logo="" group-title="General",BS TV Tokyo
This one is actually Japanet DX, streaming channels on daytime, and Japanet DX commercial announcements + shopping on nighttime.

2021-08-04 11:55 UTC, LaneSh4d0w commented on channels/jp.m3u
> +#EXTINF:-1 tvg-id="BSTVTokyo.jp" tvg-name="BS TV Tokyo" tvg-country="JP" tvg-language="Japanese" tvg-logo="" group-title="General",BS TV Tokyo
Interesting advertisments too.

https://www.shopjapan.co.jp/products/OTHR-80005/

![vlcsnap-2021-08-04-13h51m30s408](https://user-images.githubusercontent.com/30985701/128176158-44007328-cf15-4ff8-b2b6-535b01ee38e2.png)
![vlcsnap-2021-08-04-13h53m01s576](https://user-images.githubusercontent.com/30985701/128176165-77c1c105-88fa-48cd-bb26-2eb06a0c67b7.png)

Right now, Nikkei News 9 is being streamed.

2021-08-04 12:32 UTC, Dum4G requested changes

2021-08-04 12:32 UTC, Dum4G commented on channels/jp.m3u
> -#EXTINF:-1 tvg-id="TVTokyo.jp" tvg-name="TV Tokyo" tvg-country="JP" tvg-language="Japanese" tvg-logo="https://i.imgur.com/vgEnHX6.png" group-title="",TV Tokyo
It took a long time to load but it shows Tokyo MX1 now. Maybe they're switching it to TV Tokyo on schedule

2021-08-05 12:37 UTC, Dum4G approved these changes

2021-08-05 12:39 UTC, merged