Update us.m3u
iptv-org/iptv pull request #416
Opened 2019-10-05 17:23 UTC by boomski

Added Fubo Cycling

2019-10-05 22:22 UTC, freearhey requested changes

2019-10-05 22:22 UTC, freearhey commented on channels/us.m3u
> +http://ummodigital.com:8000/jorge1/jorge1/3426
This channel does not work for me.

2019-10-06 07:47 UTC, boomski commented
![test](https://user-images.githubusercontent.com/25525836/66265908-29d50500-e81e-11e9-8523-c44e60252b89.gif)

2019-10-06 14:17 UTC, freearhey commented
Honestly, I still do not understand why it works for you but not for me. Just in case, I checked the link through Postman and it also returns me 401 error.

2019-10-06 15:20 UTC, freearhey commented
@boomski can you remove the link `http://ummodigital.com:8000/jorge1/jorge1/3426` from PR so that I can approve it and keep a new logo for the FOX Business Network

2019-10-06 15:29 UTC, boomski commented
@freearhey  Link removed

2019-10-06 15:35 UTC, freearhey approved these changes

2019-10-06 15:35 UTC, merged