Update fr.m3u
iptv-org/iptv pull request #444
Opened 2019-10-07 19:57 UTC by boomski

2019-10-07 23:10 UTC, freearhey requested changes

2019-10-08 08:47 UTC, boomski commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
For me it plays in VLC without problems

2019-10-08 09:32 UTC, boomski commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
Can you play the stream on the website itself ?
https://replay.gulli.fr/Direct

2019-10-08 16:44 UTC, freearhey commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
no, they just show me this for 10 seconds:

<img width="940" alt="Screenshot 2019-10-08 at 19 40 22" src="https://user-images.githubusercontent.com/7253922/66415197-bbea3280-ea03-11e9-9089-acdf52193e19.png">

I don’t understand French, but I think it says that they won’t show me anything else.

2019-10-08 21:17 UTC, boomski commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
Probably stream is geoblocked ,its not available in your territory is the message.
I watch it from Belgium here it works , strange for a channel from France that i can watch it over here.

I Know we don't add geo streams but could we make a seperate playlist, for example geoblock.m3u and add all these links in there then user from some countries can enjoy those streams there , We could place before the channel name the country code.

For example in this case :
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://i.imgur.com/NMjuEXC.png" group-title="",FR | Gulli
https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8

And if they stop working i'm sure  some users will make notice off it , we can make some changes. What do you think?

2019-10-08 23:06 UTC, freearhey commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
I understand you, but the problem is a little more complicated. The fact is that in most cases broken links are found not by users, but by scripts. 

A couple of times a month I run a script on my computer that automatically goes through all 8000 links and checks if broadcasts are available. And for this script there is no difference the channel is geo-blocked or just does not work. The same thing with the VLC player, usually it does not even produce any errors.

At the same time, people from completely different places can use these playlists, and adding broadcasts limited to one/two countries to them seems a little unjustified to me.

That’s why I so much resist adding such links.

2019-10-08 23:21 UTC, freearhey approved these changes

2019-10-08 23:22 UTC, merged

2020-06-12 18:41 UTC, cheznewa commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
> I Know we don't add geo streams but could we make a seperate playlist, for example geoblock.m3u and ...

i'm for this geoblock.m3u, for channel are geoblocked for any country only, please create it.

2020-06-13 14:35 UTC, freearhey commented on channels/fr.m3u
> +https://gulli-hls-live.akamaized.net/gulli.isml/gulli-audio102_fre=64000-video=900000.m3u8
@cheznewa You can find out more about why we don't add geoblocked streams to the repository [here](https://github.com/iptv-org/iptv/issues/379#issuecomment-540117333) and [here](https://github.com/iptv-org/iptv/issues/480)