Update kp.m3u
iptv-org/iptv pull request #4468
Opened 2021-09-11 05:09 UTC by taodicakhia

elufatv's Twitch channel is changed into kctv_elufa (htps://www.twitch.tv/kctv_elufa)

2021-09-11 05:39 UTC, freearhey requested changes

2021-09-11 05:39 UTC, freearhey commented on channels/kp.m3u
> +https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=htps://www.twitch.tv/kctv_elufa
```suggestion
https://query-streamlink.herokuapp.com/iptv-query?streaming-ip=https://www.twitch.tv/kctv_elufa
```

2021-09-11 06:57 UTC, Sphinxroot approved these changes

2021-09-11 11:34 UTC, Dum4G commented
We can add a refferer if you know what it is. tv.nknews.org is the right one?

2021-09-11 18:12 UTC, freearhey approved these changes

2021-09-11 19:57 UTC, merged

2021-09-11 19:58 UTC, freearhey commented
@taodicakhia Thank you for help!

2021-09-12 01:24 UTC, taodicakhia commented
> We can add a refferer if you know what it is. tv.nknews.org is the right one?
Yes