Add Peace TV Network Channels
iptv-org/iptv pull request #4629
Opened 2021-09-19 21:19 UTC by fawazahmed0

2021-09-19 22:00 UTC, Dum4G requested changes
http://ysfiptv.club:8080/7YQVV9JnLY/EAhoSqJSyJ is an Xstream link that is leaked and personal with limited viewer and lifespan counts, we do not accept them

2021-09-20 09:13 UTC, fawazahmed0 commented
> 
> 
> http://ysfiptv.club:8080/7YQVV9JnLY/EAhoSqJSyJ is an Xstream link that is leaked and personal with limited viewer and lifespan counts, we do not accept them

I have removed the xstream link

2021-09-20 09:43 UTC, freearhey approved these changes

2021-09-20 11:12 UTC, Dum4G approved these changes

2021-09-20 11:13 UTC, merged

2021-09-20 11:13 UTC, Dum4G commented
Thanks for contribution!