Update fr.m3u
iptv-org/iptv pull request #4674
Opened 2021-09-23 11:38 UTC by dct-infra

Updated TF1

2021-09-23 13:31 UTC, Dum4G requested changes

2021-09-23 13:31 UTC, Dum4G commented on channels/fr.m3u
> -http://stream.tvtap.net:8081/live/fr-tf1.stream/playlist.m3u8
Works for me. We should keep both variants

2021-09-23 15:52 UTC, Dum4G approved these changes

2021-09-23 15:52 UTC, merged

2021-09-23 15:53 UTC, Dum4G commented
Removed an official link due to implemented token protection on https://www.tntendirect.com/TF1-en-direct @LaneSh4d0w

2021-09-23 15:54 UTC, LaneSh4d0w commented
Thanks for tagging me, will take a look.

2022-01-24 13:40 UTC, vartaxe commented
Tf1 seems to not work anymore

2022-01-24 13:45 UTC, dct-infra commented
@vartaxe  works through the flusonic url

2022-01-24 13:51 UTC, vartaxe commented
Oh sorry thanks ;)