Update co.m3u
iptv-org/iptv pull request #478
Opened 2019-10-10 10:53 UTC by boomski

2019-10-10 16:38 UTC, madtom75 commented
Hi I’m desperately looking for KTLA5 and KCAL9 IPTV, any help?

2019-10-10 17:32 UTC, freearhey requested changes

2019-10-10 17:32 UTC, freearhey commented on channels/co.m3u
> +https://rcnhd.cdn.net.co/live01/rcnhd_720p.m3u8
does not work in VLC player

2019-10-10 21:39 UTC, boomski commented
Oke, but nothing is wrong with the stream because on other platforms it plays , it is just on VLC it doesn't work. so we could add it  with a tag behind the name [NO VLC] , like we did in hr.m3u playlist where a lot of channels don't play in Kodi they are tagged  [NO KODI] , and they work in VLC .
What do you think ?

2019-10-11 00:12 UTC, freearhey commented
@boomski I thought we decided not to add translations that do not work in VLC or Kodi. 
As for the channels in hr.m3u, in this case I think they should be deleted. Unless you mind of course.

2019-10-11 00:32 UTC, boomski commented
I should keep the channels in the lists in hr.m3u they work and it says NO KODI so users know it will not work on the mentioned platform. It is a little bit the same discussion as the geoblocked url maybe we should ask other users their opinion about this and which app or program they use for watching?

2019-10-11 04:16 UTC, freearhey commented
Ok, let's ask others.

2019-10-15 15:14 UTC, closed without merging