Update ua.m3u
iptv-org/iptv pull request #4844
Opened 2021-10-02 10:15 UTC by Sphinxroot

2021-10-02 13:14 UTC, dct-infra requested changes
https://www.youtube.com/c/pryamiy/live would be a better fit.

2021-10-04 09:50 UTC, Dum4G commented on channels/ua.m3u
> +https://iptv.dc-team.com/query?url=https://www.youtube.com/channel/UCH9H_b9oJtSHBovh94yB5HA/live
```suggestion
http://free.fullspeed.tv/query?url=https://www.youtube.com/channel/UCH9H_b9oJtSHBovh94yB5HA/live
```

2021-10-04 09:51 UTC, Dum4G approved these changes

2021-10-04 10:24 UTC, LaneSh4d0w approved these changes

2021-10-04 10:25 UTC, merged