Add Channels br
iptv-org/iptv pull request #4972
Opened 2021-10-09 22:29 UTC by allanf181

2021-10-10 21:33 UTC, allanf181 commented
> ![image](https://user-images.githubusercontent.com/30985701/136708514-7c331b8d-b1a9-428a-9286-85a2063d1762.png) This port really doesn't answer for me.

![image](https://user-images.githubusercontent.com/14101716/136713615-b3e8c411-2ba3-4050-a2cc-10623714fb92.png)

2021-10-14 16:13 UTC, freearhey requested changes

2021-10-14 18:57 UTC, freearhey requested changes

2021-10-14 19:00 UTC, freearhey requested changes

2021-10-15 03:17 UTC, freearhey submitted a review, later dismissed

2021-10-15 07:51 UTC, LaneSh4d0w commented
Before I approve, shall I fix the other uol.br links with the user agent ?

2021-10-16 17:14 UTC, BellezaEmporium approved these changes

2021-10-16 17:28 UTC, freearhey approved these changes

2021-10-16 17:28 UTC, merged