IR : Bring back iFilm English
iptv-org/iptv pull request #5022
Opened 2021-10-14 07:53 UTC by BellezaEmporium

Safe to say it's back again.

Closes #4870

2021-10-15 11:32 UTC, Dum4G approved these changes

2021-10-15 11:33 UTC, Dum4G requested changes
Geo-blocked

2021-10-18 02:20 UTC, Dum4G approved these changes

2021-10-23 23:26 UTC, jkemp814 approved these changes

2021-10-23 23:58 UTC, merged