Update us.m3u
iptv-org/iptv pull request #5137
Opened 2021-10-22 21:05 UTC by freearhey

Closes #4928
Closes #5085

2021-10-22 21:50 UTC, BellezaEmporium submitted a review, later dismissed

2021-10-23 22:28 UTC, MapGuy11 requested changes
The link works

2021-10-23 23:12 UTC, jkemp814 submitted a review, later dismissed

2021-10-24 00:26 UTC, LaneSh4d0w commented
> 
> 
> > > The link works
> > 
> > 
> > Which link ?
> 
> #EXTINF:-1 tvg-id="WTGSTV.us" tvg-country="US" tvg-language="English" tvg-logo="https://upload.wikimedia.org/wikipedia/en/9/99/FOX28WTGS.PNG" group-title="Local",FOX 28 Savannah GA (WTGS) (720p) https://content.uplynk.com/channel/e56ba52a1b9d45ad8c8a033fd83fe480.m3u8

Infinite "we will be right back" for me now.

2021-10-24 00:45 UTC, freearhey commented
@MapGuy11 I put the link back.

2021-10-24 00:58 UTC, MapGuy11 approved these changes

2021-10-24 04:44 UTC, jkemp814 approved these changes

2021-10-24 04:49 UTC, merged