Update ca.m3u
iptv-org/iptv pull request #5150
Opened 2021-10-23 05:00 UTC by freearhey

Closes #5148

2021-10-23 22:09 UTC, BellezaEmporium submitted a review, later dismissed

2021-10-23 23:08 UTC, jkemp814 submitted a review, later dismissed

2021-10-23 23:33 UTC, MapGuy11 requested changes
I have also a non Geo-Blocked Url for all the other folks:
https://cdn87.theus6tv.tk/Canada/cable/cbcnewsnetwork.m3u8

2021-10-24 00:36 UTC, freearhey commented
@MapGuy11 Thanks! I added a link to the playlist.

2021-10-24 00:41 UTC, MapGuy11 approved these changes

2021-10-24 00:43 UTC, jkemp814 approved these changes

2021-10-24 00:43 UTC, merged