Update fr.m3u
iptv-org/iptv pull request #5152
Opened 2021-10-23 07:30 UTC by mh292929

remove 2 channels because channel names change

2021-10-23 11:26 UTC, dct-infra requested changes
Thank you for your contribution.
Why would we remove WORKING channels? An update would be more relevant.
Feel free to update the channels according to their current state/name/logo/type but don't just remove.

2021-10-23 19:56 UTC, freearhey approved these changes

2021-10-23 23:06 UTC, jkemp814 approved these changes

2021-10-24 03:27 UTC, dct-infra approved these changes

2021-10-24 04:37 UTC, merged