ALL : Begin gathering channels from #5190
iptv-org/iptv pull request #5265
Opened 2021-11-01 23:12 UTC by LaneSh4d0w

2021-11-02 02:37 UTC, Sophgirl41 commented
Please add rewindtv back

2021-11-10 07:30 UTC, freearhey requested changes

2021-11-10 07:30 UTC, freearhey commented on channels/cl.m3u
> +https://593b04c4c5670.streamlock.net/8104/8104/playlist.m3u8
![image](https://user-images.githubusercontent.com/7253922/141068504-23363378-7c8e-4bf4-ba69-3e48386bdb22.png)

2021-11-10 07:30 UTC, freearhey commented on channels/cl.m3u
> +https://5eff35271151c.streamlock.net:1936/8056/8056/playlist.m3u8
![image](https://user-images.githubusercontent.com/7253922/141068731-24bce90f-300d-4df6-bbc7-7c1a783b90c8.png)

2021-11-15 20:42 UTC, freearhey approved these changes

2021-11-15 21:10 UTC, sguinetti approved these changes

2021-11-15 21:18 UTC, merged