Update ec.m3u
iptv-org/iptv pull request #5278
Opened 2021-11-03 02:59 UTC by sguinetti

This PR adds El Sol Radio y Television from http://www.elsolradiotv.com/

2021-11-03 09:30 UTC, LaneSh4d0w approved these changes, later dismissed

2021-11-04 03:11 UTC, freearhey requested changes

2021-11-04 03:11 UTC, freearhey commented on channels/ec.m3u
> +https://streaming5.globalhostla.com/rtplive/elsolrad/playlist.m3u8
![image](https://user-images.githubusercontent.com/7253922/140251615-ec898395-3d76-4538-9b79-0ee3fff445cc.png)
```suggestion
http://streaming5.globalhostla.com/rtplive/elsolrad/playlist.m3u8
```

2021-11-04 18:32 UTC, LaneSh4d0w approved these changes

2021-11-05 02:43 UTC, freearhey approved these changes

2021-11-05 02:44 UTC, merged