IN : Scrape channels from Tulix
iptv-org/iptv pull request #5289
Opened 2021-11-03 16:28 UTC by LaneSh4d0w

2021-11-03 23:02 UTC, Dum4G approved these changes

2021-11-07 09:26 UTC, freearhey requested changes

2021-11-07 09:26 UTC, freearhey commented on channels/in.m3u
> +https://dvrfl02.tulix.tv/gfaith-divine/playlist.m3u8
Doesn't work

2021-11-07 09:26 UTC, freearhey commented on channels/in.m3u
> +https://dvrfl02.tulix.tv/gfaith-harvestmalayalam/playlist.m3u8
Doesn't work

2021-11-07 09:26 UTC, freearhey commented on channels/in.m3u
> +https://live.wmncdn.net/harvestenglish/d1796a22d24e8696c7d5d0b5c349fdd2.sdp/playlist.m3u8
Work

2021-12-03 09:05 UTC, closed without merging