Update ve.m3u
iptv-org/iptv pull request #5376
Opened 2021-11-14 19:06 UTC by sguinetti

This PR adds VPItv from Youtube channel

2021-11-14 20:40 UTC, LaneSh4d0w submitted a review, later dismissed

2021-11-15 19:32 UTC, freearhey requested changes

2021-11-15 19:32 UTC, freearhey commented on channels/ve.m3u
> +https://query-streamlink-us.herokuapp.com/iptv-query?streaming-ip=https://www.dailymotion.com/vpitv
![image](https://user-images.githubusercontent.com/7253922/141842628-d5564dbb-c281-4304-8bb2-ffc694f51a25.png)

2021-11-15 19:37 UTC, freearhey approved these changes

2021-11-15 19:54 UTC, dct-infra approved these changes

2021-11-15 20:01 UTC, merged