Update ua.m3u
iptv-org/iptv pull request #5412
Opened 2021-11-18 16:59 UTC by OwElko

added missing logo

2021-11-18 18:38 UTC, dct-infra submitted a review, later dismissed

2021-11-18 23:47 UTC, Dum4G requested changes
Wrong pic from Russian channel. Must look like this
https://1plus1.video/static/player/i/logo/color/sport.svg
https://1plus1.video/tvguide/sport/online

2021-11-18 23:48 UTC, Dum4G approved these changes

2021-11-20 12:53 UTC, LaneSh4d0w approved these changes

2021-11-20 12:54 UTC, merged