Add itoon channel
iptv-org/iptv pull request #5568
Opened 2021-12-03 16:01 UTC by mrbooshehri

2021-12-03 17:25 UTC, fershady reviewed
I have make a logo https://i.imgur.com/2HoOHwF.png

2021-12-04 01:52 UTC, MapGuy11 commented
@mrbooshehri ADD logo thanks then approve.

2021-12-04 15:02 UTC, LaneSh4d0w commented on channels/ir.m3u
> +#EXTINF:-1 tvg-id="itoon" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Kids" (480p)
```suggestion
#EXTINF:-1 tvg-id="itoon" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Kids" (480p), iToon
```

Missing part of identification.

2021-12-04 15:02 UTC, LaneSh4d0w requested changes
See attached commit suggestion.

2021-12-04 17:55 UTC, Dum4G commented on channels/ir.m3u
> +#EXTINF:-1 tvg-id="itoon" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Kids", iToon (480p)
```suggestion
#EXTINF:-1 tvg-id="iToon.ir" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Kids",iToon (480p)
```

2021-12-04 17:55 UTC, Dum4G approved these changes, later dismissed

2021-12-04 17:56 UTC, Dum4G commented on channels/ir.m3u
> +#EXTINF:-1 tvg-id="iToon.ir" tvg-country="IR" tvg-language="Persian" tvg-logo="" group-title="Kids",iToon (480p)
```suggestion
#EXTINF:-1 tvg-id="iToon.ir" tvg-country="IR" tvg-language="Persian" tvg-logo="https://i.imgur.com/2HoOHwF.png" group-title="Kids",iToon (480p)
```

2021-12-04 17:56 UTC, Dum4G approved these changes

2021-12-04 18:03 UTC, LaneSh4d0w approved these changes

2021-12-04 18:09 UTC, merged