Update ni.m3u
iptv-org/iptv pull request #5651
Opened 2021-12-10 05:43 UTC by fershady

2021-12-10 10:39 UTC, Dum4G commented on channels/ni.m3u
> +http://ott.streann.com:8080/loadbalancer/services/public/channels/59e60c4997381ef50d15c041/playlist.m3u8
broadcasts black screen

2021-12-10 10:43 UTC, Dum4G requested changes

2021-12-10 10:43 UTC, Dum4G commented on channels/ni.m3u
> +#EXTINF:-1 tvg-id="MasTV.ni" tvg-country="NI" tvg-language="Spanish" tvg-logo="" group-title="",MasTV (Canal 23) [Offline]
MasTV (Canal 23) is a Puerto-Rican channel, shouldn't be there and wi;ll be fixed in https://github.com/iptv-org/iptv/pull/5653

2021-12-11 06:26 UTC, Dum4G approved these changes

2021-12-11 10:29 UTC, LaneSh4d0w approved these changes

2021-12-11 10:31 UTC, merged