Add French Canadian Channel
iptv-org/iptv pull request #5851
Opened 2021-12-23 03:45 UTC by gabrielbergeron

This is a french channel from Quebec in Canada.

I found the stream link on their website https://www.qub.ca/tvaplus/video/lcn-en-direct-1043085510

It's Geo-Blocked but it works from where I am.
![image](https://user-images.githubusercontent.com/6955416/147184962-83610c10-6004-4fc1-aec7-b54b27ec8277.png)

2021-12-23 05:53 UTC, Dum4G requested changes

2021-12-23 05:53 UTC, Dum4G commented on channels/ca.m3u
> +#EXTINF:-1 tvg-id="LCN(src01).ca" tvg-country="CA" tvg-language="French" tvg-logo="https://i.imgur.com/JHOyrgA.png" group-title="",LCN [Geo-blocked]
```suggestion
#EXTINF:-1 tvg-id="LCN.ca" tvg-country="CA" tvg-language="French" tvg-logo="https://i.imgur.com/JHOyrgA.png" group-title="",LCN [Geo-blocked]
```

2021-12-23 16:56 UTC, LaneSh4d0w approved these changes
I would have thought from the name of the stream that this was TVA Nouvelles, but indeed it doesn't seem to be. It's from the same group however.

2021-12-23 17:10 UTC, gabrielbergeron commented
No LCN is a channel owned by the same company, they sometime broadcast the same content, but they are seperate channels.

For the TVG-ID I wasn't sure what it was I searched a lot, I put LCN(src01).ca since it's all I could find.

2021-12-23 20:20 UTC, Dum4G approved these changes

2021-12-24 13:17 UTC, freearhey approved these changes

2021-12-24 13:17 UTC, merged