Add Alternate FOX Weather
iptv-org/iptv pull request #5926
Opened 2021-12-31 18:46 UTC by MapGuy11

Add a second FOX Weather stream from Tubi.TV (a FOX Owned Streaming Service). The key will be automatically generated when you visit the URL.

2021-12-31 19:13 UTC, LaneSh4d0w approved these changes

2021-12-31 19:57 UTC, Dum4G commented
Should belong to us_tubi.m3u I guess

2021-12-31 20:00 UTC, LaneSh4d0w commented
Ah yep.

2021-12-31 20:24 UTC, dct-infra approved these changes, later dismissed

2022-01-01 01:24 UTC, LaneSh4d0w requested changes
to put on us_tubi.m3u

2022-01-01 01:46 UTC, LaneSh4d0w approved these changes

2022-01-01 01:46 UTC, Dum4G approved these changes

2022-01-01 01:58 UTC, merged