Update us.m3u
iptv-org/iptv pull request #6006
Opened 2022-01-06 01:39 UTC by what-a

Scrubbed PBS naming and logos. There was duplicate entry (i.e. same stream listed twice) for PBS Allentown PA, so I deleted one.

2022-01-06 07:10 UTC, Dum4G submitted a review, later dismissed

2022-01-06 08:51 UTC, freearhey requested changes
All logos from `image.pbs.org` are geo-blocked.

![image](https://user-images.githubusercontent.com/7253922/148355803-2ca6a54e-1dae-45de-a2f1-7b1e1d4dd959.png)

2022-01-06 09:34 UTC, Central302 commented
(Alternative Logo Data From DirecTV EPG)
https://www.directv.com/images/logos/channels/dark/large/022.png

2022-01-06 14:46 UTC, MapGuy11 commented
Something was screwy with my review please dismiss my commit.

2022-01-07 08:50 UTC, Dum4G approved these changes

2022-01-07 08:59 UTC, freearhey approved these changes

2022-01-07 09:18 UTC, merged