BD : Fix streams + move JagoBD channels to playlist
iptv-org/iptv pull request #6060
Opened 2022-01-12 14:01 UTC by LaneSh4d0w

2022-01-12 14:25 UTC, LaneSh4d0w commented
I'll need to ask why some channels are Geo-Blocked. Channel I works on my side, said to be geo-locked.

2022-01-12 16:34 UTC, Dum4G commented
Can confirm, Channel I is working for me

2022-01-14 05:25 UTC, Sphinxroot submitted a review, later dismissed

2022-01-16 19:43 UTC, freearhey approved these changes, later dismissed

2022-01-17 06:16 UTC, Dum4G requested changes

2022-01-17 06:16 UTC, Dum4G commented on channels/bd_jagobd.m3u
> +#EXTINF:-1 tvg-id="ATNBanglaUK.bd" tvg-country="UK" tvg-language="Bengali" tvg-logo="http://atnbanglauk.tv/wp-content/uploads/2015/04/sized1.png" group-title="General",ATN Bangla UK (576p) [Geo-block
is not geo-blocked for me

2022-01-17 06:16 UTC, Dum4G commented on channels/bd_jagobd.m3u
> +#EXTINF:-1 tvg-id="Channel9.bd" tvg-country="BD" tvg-language="Bengali" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/f/ff/Channel9_bd.svg/350px-Channel9_bd.svg.png" group-title="Local",C
is not geo-blocked for me

2022-01-17 06:16 UTC, Dum4G commented on channels/bd_jagobd.m3u
> +#EXTINF:-1 tvg-id="ChannelI.bd" tvg-country="BD" tvg-language="Bengali" tvg-logo="https://www.channelionline.com/wp-content/uploads/2019/07/channel-i-logo-1.png" group-title="General",Channel I (1080
is not geo-blocked for me

2022-01-17 06:16 UTC, Dum4G commented on channels/bd_jagobd.m3u
> +https://live.jagobd.com:444/c3VydmVyX8RpbEU9Mi8xNy8yMDE0GIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PTOmdFsaWRtaW51aiPhnPTI/dbcnews.stream/playlist.m3u8
is not geo-blocked for me

2022-01-17 09:33 UTC, Dum4G approved these changes

2022-01-17 13:02 UTC, freearhey approved these changes

2022-01-17 13:02 UTC, merged