Update US.m3u
iptv-org/iptv pull request #6125
Opened 2022-01-19 12:15 UTC by Central302

This Patch Will Fix WMAQ-TV News.
Source : https://www.nbcchicago.com/news/local/watch-live-nbc-5-news-3/2187917/

2022-01-19 14:32 UTC, freearhey requested changes

2022-01-19 14:32 UTC, freearhey commented on channels/us.m3u
> +#EXTINF:-1 tvg-id="KNBCNews.us" tvg-country="US" tvg-language="English" tvg-logo="" group-title="Local", NBC4 KNBC-TV News (1080p)
```suggestion
#EXTINF:-1 tvg-id="KNBCNews.us" tvg-country="US" tvg-language="English" tvg-logo="" group-title="Local",NBC4 KNBC-TV News (1080p)
```

2022-01-19 18:52 UTC, freearhey approved these changes

2022-01-20 02:19 UTC, Sphinxroot approved these changes

2022-01-20 02:19 UTC, merged