Update pk.m3u
iptv-org/iptv pull request #6139
Opened 2022-01-20 08:55 UTC by Sphinxroot

ARY Digital and News are working for me but tag was  [Offline]

2022-01-20 09:01 UTC, Dum4G requested changes
You can safely clean those links from definst part and arguments that come after ?

2022-01-20 09:11 UTC, Sphinxroot commented
> You can safely clean those links from definst part and arguments that come after ?

if i remove it  it dont play well  .. i get audio feed only and no image , if i let it there it take 10 sec to show up but image is there

2022-01-21 22:00 UTC, Dum4G approved these changes

2022-01-24 09:46 UTC, dct-infra approved these changes

2022-01-24 09:56 UTC, Central302 approved these changes

2022-01-24 13:08 UTC, merged