Update ca.m3u
iptv-org/iptv pull request #6441
Opened 2022-02-16 11:16 UTC by Central302

This Patch WIll
●Remove Canadian Server m3u8 (404 Not Found)
●Replace CP24 and The Weather Network (Sorry, it's Not National Feed, It's Hard to Find)

2022-02-16 14:13 UTC, what-a approved these changes, later dismissed

2022-02-16 14:41 UTC, LaneSh4d0w commented
TSN : http://s1.mysportz.tv:2082/tsn1/playlist.m3u8 / http://s1.mysportz.tv:2082/tsn2/playlist.m3u8 / http://s1.mysportz.tv:2082/tsn3/playlist.m3u8 / http://s1.mysportz.tv:2082/tsn4/playlist.m3u8 / http://s1.mysportz.tv:2082/tsn5/playlist.m3u8

2022-02-16 21:47 UTC, Central302 commented
Fixed TSN.

2022-02-18 10:06 UTC, freearhey requested changes

2022-02-18 11:39 UTC, freearhey approved these changes

2022-02-18 12:18 UTC, MapGuy11 approved these changes

2022-02-18 12:18 UTC, merged

2025-04-06 04:14 UTC, seoul98 commented
https://github.com/iptv-org/iptv/pull/6441#issuecomment-1041562085