Add & replace streams
iptv-org/iptv pull request #6479
Opened 2022-02-21 20:23 UTC by fershady

2022-02-22 10:12 UTC, freearhey commented
The last commits only resolves the conflict caused by updating the repository structure.

2022-02-22 11:23 UTC, freearhey requested changes

2022-02-22 11:23 UTC, freearhey commented on streams/sv.m3u
> +#EXTINF:-1 tvg-id="TaberTV.sv",Taber TV
```suggestion
#EXTINF:-1 tvg-id="TaberTV.sv",Taber TV [Geo-blocked]
```
Without a VPN I get an error:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/7253922/155122571-5dcee9f6-760d-4f18-ac99-0e1ed38ed8d3.png">

2022-02-23 03:13 UTC, freearhey approved these changes

2022-03-01 17:50 UTC, LaneSh4d0w commented on streams/sv.m3u
> +https://tvserver.ml:1443/tvca/live/playlist.m3u8
Timeout, no answer from the server. Not 24/7 ?

2022-03-18 14:11 UTC, freearhey commented
Closed in favor #6759

2022-03-18 14:11 UTC, closed without merging