Replaced  the links of 2 channels
iptv-org/iptv pull request #6614
Opened 2022-03-06 13:41 UTC by Manipulativemachan

2022-03-06 18:25 UTC, MapGuy11 commented on streams/in.m3u
> +http://131.153.22.8:1935/NCV/ncvstream/chunklist_w509930903.m3u8
http://131.153.22.8:1935/NCV/ncvstream/playlist.m3u8

2022-03-06 18:25 UTC, MapGuy11 commented on streams/in.m3u
> +http://131.153.22.8:1935/SWANTHAM/live/chunklist_w436483673.m3u8
http://131.153.22.8:1935/SWANTHAM/live/playlist.m3u8

2022-03-06 18:26 UTC, MapGuy11 requested changes

2022-03-06 18:26 UTC, MapGuy11 commented on streams/in.m3u
> +http://131.153.22.8:1935/NCV/ncvstream/chunklist_w509930903.m3u8
http://131.153.22.8:1935/NCV/ncvstream/playlist.m3u8

2022-03-06 18:26 UTC, MapGuy11 commented on streams/in.m3u
> +http://131.153.22.8:1935/SWANTHAM/live/chunklist_w436483673.m3u8
http://131.153.22.8:1935/SWANTHAM/live/playlist.m3u8

2022-03-06 23:39 UTC, MapGuy11 commented
@Manipulativemachan are you going to fix this?

2022-03-07 05:21 UTC, Manipulativemachan commented
> @Manipulativemachan are you going to fix this?

Please make the changes.

2022-03-07 07:27 UTC, LaneSh4d0w commented on streams/in.m3u
> +http://131.153.22.8:1935/NCV/ncvstream/chunklist_w509930903.m3u8
```suggestion
http://131.153.22.8:1935/NCV/ncvstream/playlist.m3u8
```

2022-03-07 07:27 UTC, LaneSh4d0w commented on streams/in.m3u
> +http://131.153.22.8:1935/SWANTHAM/live/chunklist_w436483673.m3u8
http://131.153.22.8:1935/SWANTHAM/live/playlist.m3u8

2022-03-07 07:27 UTC, LaneSh4d0w commented on streams/in.m3u
> +http://131.153.22.8:1935/SWANTHAM/live/chunklist_w436483673.m3u8
```suggestion
http://131.153.22.8:1935/SWANTHAM/live/playlist.m3u8
```

2022-03-07 07:28 UTC, LaneSh4d0w approved these changes

2022-03-07 08:55 UTC, its0x08 approved these changes

2022-03-07 12:25 UTC, MapGuy11 approved these changes

2022-03-07 12:26 UTC, merged