ES: Add 7 Noticias (YouTube)
iptv-org/iptv pull request #6692
Opened 2022-03-13 13:21 UTC by joaquinito2048

2022-03-16 07:52 UTC, LaneSh4d0w approved these changes, later dismissed
Watch out as Heroku might take it down whether they like it.

2022-03-18 13:44 UTC, freearhey requested changes
Please check the links again.

2022-03-18 13:44 UTC, freearhey commented on streams/es.m3u
> +https://streamlink-iptv.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCCydt40S3mVi9YXQJjK8Nsw/live
<img width="752" alt="image" src="https://user-images.githubusercontent.com/7253922/159013801-6f9a501b-8f64-4eb7-8c67-97a525f474d3.png">

2022-03-18 13:44 UTC, freearhey commented on streams/es.m3u
> +https://streamlink-iptv.herokuapp.com/iptv-query?streaming-ip=https://www.twitch.tv/7nntv
<img width="754" alt="image" src="https://user-images.githubusercontent.com/7253922/159013860-649c7cb9-ec0f-46f2-9c80-d6c7ed1afd50.png">

2022-03-18 21:17 UTC, LaneSh4d0w commented
As I've predicted, Heroku most certainly took it down.

2022-03-18 21:17 UTC, LaneSh4d0w commented on streams/es.m3u
> +https://streamlink-iptv.herokuapp.com/iptv-query?streaming-ip=https://www.youtube.com/channel/UCCydt40S3mVi9YXQJjK8Nsw/live
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCCydt40S3mVi9YXQJjK8Nsw/live

2022-03-18 21:18 UTC, LaneSh4d0w commented on streams/es.m3u
> +https://streamlink-iptv.herokuapp.com/iptv-query?streaming-ip=https://www.twitch.tv/7nntv
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/7nntv

2022-03-19 10:18 UTC, joaquinito2048 commented
@LaneSh4d0w @freearhey Approve and merge.

2022-03-19 11:53 UTC, freearhey approved these changes

2022-03-19 19:03 UTC, LaneSh4d0w reviewed
Cannot test if links are online, server returns 502.

2022-03-19 19:10 UTC, MapGuy11 approved these changes

2022-03-19 19:10 UTC, merged