Update us.m3u [ABC, CBS, FOX, NBC, Other US Sport Channels]
iptv-org/iptv pull request #6956
Opened 2022-04-03 18:27 UTC by Bobcool101

This patch has a bunch of different regional ABC, CBS, FOX, NBC Networks. It also include, ACCN, ESPN, ESPN 2, ESPNNEWS, ESPNU, FS1, MSG, BTN, SECN, and NBA Gamepass.

2022-04-03 21:46 UTC, its0x08 submitted a review, later dismissed

2022-04-04 10:01 UTC, Central302 requested changes

2022-04-04 10:01 UTC, Central302 commented on streams/us.m3u
> +http://104.238.221.56:8080/live/823868279/9507295574/6014.m3u8?token=Q0dRVxcMEAMbCFkFVABTAVAAVAUBVlUMUAdSVgcDDFtaVl1UB1IDDgEbTRBDQBdXVF5vCFBACQ4CBFAbQERGXEo6UFJGXhAIDApRBggWSRBBWl0EFlgDFBBFDVNACxcLDF
FOX Sports Channels Are Not Allowed (Blacklisted Due to DMCA, See [Below](https://github.com/iptv-org/database/blob/master/data/blocklist.csv)

2022-04-04 10:01 UTC, Central302 commented on streams/us.m3u
> +https://msggo-live.net/v1/manifest/1a954fea9a9e371ab24e8226b756520725bb3f2d/MSGN-LIVE-001/ef513621-4497-4898-9a49-89d812b10faa/0.m3u8
MSG, But Tokened and USA IP ONLY.

2022-04-04 13:42 UTC, Bobcool101 commented
Changes requested by Central302 have been added

2022-04-05 11:33 UTC, LaneSh4d0w requested changes
I have 404s on the https://d17f1mg1q6g54e.cloudfront.net/ links

2022-04-05 13:25 UTC, Bobcool101 commented
> I have 404s on the https://d17f1mg1q6g54e.cloudfront.net/ links

Its because that team is not currently playing a game, wait until a team starts playing and you'll be able to watch. I linked a 24/7 nbatv stream in there to show it works: https://d17f1mg1q6g54e.cloudfront.net/hls/nbatv/chunks.m3u8

2022-04-05 13:26 UTC, LaneSh4d0w commented
OK.

2022-04-05 13:26 UTC, LaneSh4d0w approved these changes

2022-04-05 14:52 UTC, what-a approved these changes

2022-04-06 21:44 UTC, Central302 approved these changes

2022-04-07 08:20 UTC, merged