Update co.m3u
iptv-org/iptv pull request #7220
Opened 2022-05-02 21:22 UTC by thetucan1

- Update  Canal CNC Pasto
- Add Galeras Tv
- Add Hits Chanel
- Add sentimiento vallenato
- Add Son Corazon
- Add Son Latino
- Add Son Popular

----From https://www.cncpasto.com/
🟨🟦🟥▪▪▪▪▪

2022-05-03 00:30 UTC, what-a commented
Not playing for me in California. Geo-blocked?

2022-05-03 17:43 UTC, LaneSh4d0w approved these changes
Works for me, UK IP.

2022-05-06 16:10 UTC, dct-infra reviewed
all hvt links err on me, geoblocked?

2022-05-15 16:57 UTC, LaneSh4d0w requested changes
on second testing, hvtrafico ddns links stopped working.

2022-05-15 20:42 UTC, its0x08 submitted a review, later dismissed

2022-05-16 14:48 UTC, freearhey requested changes

2022-05-16 14:48 UTC, freearhey commented on streams/co.m3u
> +https://hvtrafico.ddns.net/pastocnc7/cnc7/playlist.m3u8
<img width="680" alt="image" src="https://user-images.githubusercontent.com/7253922/168620497-44c61aa9-f46b-49cc-9980-6074ef92fd56.png">

2022-05-21 10:44 UTC, LaneSh4d0w approved these changes, later dismissed

2022-05-21 20:20 UTC, freearhey requested changes
Please check the marked link again.

2022-05-21 20:20 UTC, freearhey commented on streams/co.m3u
> +http://190.93.137.61:1935/live/canal6/playlist.m3u8
<img width="670" alt="image" src="https://user-images.githubusercontent.com/7253922/169667738-260f8625-35b8-4e5b-9a44-73322bf2d14f.png">

2022-05-21 21:18 UTC, LaneSh4d0w approved these changes

2022-05-22 15:07 UTC, freearhey approved these changes

2022-05-22 15:48 UTC, merged