RU : add Pervvykanal
iptv-org/iptv pull request #7227
Opened 2022-05-03 17:31 UTC by LaneSh4d0w

Also know as Kanal 1 outside.

2022-05-03 17:37 UTC, freearhey requested changes

2022-05-03 17:37 UTC, freearhey commented on streams/ru.m3u
> +#EXTINF:-1 tvg-id="Pervvykanal.ru" status="online",1 (540p) [Not 24/7]
```suggestion
#EXTINF:-1 tvg-id="ChannelOne.ru" status="online",1 (540p) [Not 24/7]
```
https://iptv-org.github.io/?q=%22Channel%20One%22

2022-05-03 17:37 UTC, freearhey commented on streams/ru.m3u
> +http://31.128.159.41:8080/domashniy/playlist.m3u8
<img width="673" alt="image" src="https://user-images.githubusercontent.com/7253922/166508114-1c7e63bb-5539-4a76-8670-1ae80864d9ce.png">

2022-05-03 18:40 UTC, freearhey approved these changes

2022-05-04 14:46 UTC, what-a approved these changes

2022-05-04 14:49 UTC, merged