Extracted euronews streams
iptv-org/iptv pull request #7364
Opened 2022-05-25 12:55 UTC by pimboli

2022-05-25 18:52 UTC, BountyChocolate123456 commented on streams/euronews.m3u
> +#EXTINF:-1 tvg-id="EuronewsEnglish.fr" status="online",Euronwews French
```suggestion
#EXTINF:-1 tvg-id="EuronewsFrench.fr" status="online",Euronews French
```

2022-05-25 18:52 UTC, BountyChocolate123456 commented on streams/euronews.m3u
> +#EXTINF:-1 tvg-id=EuronewsGerman.fr" status="online",Euronews German
```suggestion
#EXTINF:-1 tvg-id=EuronewsEnglish.fr" status="online",Euronews English
https://euronews.alteox.app/hls/en_stream.m3u8
#EXTINF:-1 tvg-id=EuronewsGerman.fr" status="online",Euronews German
```

2022-05-25 18:56 UTC, BountyChocolate123456 commented on streams/euronews.m3u
> +https://euronews.alteox.app/hls/fr_stream.m3u8
```suggestion
https://euronews.alteox.app/hls/fr_stream.m3u8
#EXTINF:-1 tvg-id="EuronewsRussian.fr" status="online",Euronews Russian
https://euronews.alteox.app/hls/ru_stream.m3u8
```

2022-05-25 18:58 UTC, BountyChocolate123456 commented
Thanks @pimboli for your help. I fixed the Euronews French tvg-id and added Euronews English & Euronews Russian

2022-05-25 18:59 UTC, BountyChocolate123456 requested changes

2022-05-25 19:01 UTC, BountyChocolate123456 commented on streams/euronews.m3u
> +#EXTINF:-1 tvg-id=EuronewsEnglish.fr" status="online",Euronews English
```suggestion
#EXTINF:-1 tvg-id="EuronewsEnglish.fr" status="online",Euronews English
```

2022-05-25 19:01 UTC, BountyChocolate123456 commented on streams/euronews.m3u
> +#EXTINF:-1 tvg-id=EuronewsGerman.fr" status="online",Euronews German
```suggestion
#EXTINF:-1 tvg-id="EuronewsGerman.fr" status="online",Euronews German
```

2022-05-25 19:03 UTC, BountyChocolate123456 approved these changes, later dismissed

2022-05-26 18:25 UTC, its0x08 submitted a review, later dismissed

2022-05-28 18:36 UTC, what-a approved these changes, later dismissed

2022-05-28 22:03 UTC, freearhey requested changes
Please change the file name to `fr_euronews.m3u` to match the others.

2022-05-29 19:19 UTC, LaneSh4d0w approved these changes, later dismissed

2022-05-29 19:20 UTC, LaneSh4d0w approved these changes

2022-05-29 19:30 UTC, what-a approved these changes

2022-05-30 11:26 UTC, freearhey approved these changes

2022-05-30 11:26 UTC, merged