Update MBC 2 Flux
iptv-org/iptv pull request #7386
Opened 2022-05-29 18:23 UTC by VoXaN24

2022-05-30 11:31 UTC, freearhey approved these changes

2022-05-30 12:42 UTC, its0x08 approved these changes

2022-05-30 20:08 UTC, LaneSh4d0w requested changes
gets 403'd over some time + Xtream-Codes server.
![image](https://user-images.githubusercontent.com/30985701/171054301-02b40d0b-59e1-408c-b1f9-5bd83e99d1e3.png)

2022-06-01 20:37 UTC, LaneSh4d0w commented on streams/ae.m3u
> +http://multies.xyz:8000/live/22-5-MbC2-Mx-AcT/G8bwyFcnsM/106.m3u8
The zina link 403s on my side.

2022-06-02 14:29 UTC, LaneSh4d0w commented on streams/ae.m3u
> +http://multies.xyz:8000/live/22-5-MbC2-Mx-AcT/G8bwyFcnsM/106.m3u8
If you talked about the second link, it's from an Xtream-Codes server. Those are quite sketchy in terms of how they work, hence why I didn't accept this PR.

2022-06-04 08:31 UTC, BountyChocolate123456 approved these changes

2022-06-04 14:50 UTC, LaneSh4d0w reviewed
Quite reticent in the idea of adding an Xtream-Codes server in our playlists.

2022-06-04 14:50 UTC, LaneSh4d0w approved these changes

2022-06-04 14:51 UTC, merged