CO : update names & add Cablenoticias
iptv-org/iptv pull request #7395
Opened 2022-05-30 14:26 UTC by LaneSh4d0w

Close #7392

2022-05-31 21:15 UTC, LaneSh4d0w commented
Merged the "teveo" PRs. Cuban links should work too.

2022-06-01 20:28 UTC, freearhey requested changes
Please check the marked links again.

2022-06-01 20:29 UTC, LaneSh4d0w commented on streams/co.m3u
> +http://66.240.236.26:1935/canalpycvivo/canalpycvivo/canalpycvivo/playlist.m3u8
Used to work yesterday, maybe they do not stream 24/7.

2022-06-01 20:39 UTC, freearhey approved these changes

2022-06-02 11:49 UTC, LaneSh4d0w commented on streams/co.m3u
> +http://66.240.236.26:1935/canalpycvivo/canalpycvivo/canalpycvivo/playlist.m3u8
![image](https://user-images.githubusercontent.com/30985701/171622925-e4fe6a8a-6f0a-4aae-b9d7-04a577242b0d.png)

Now works.

2022-06-02 14:10 UTC, what-a approved these changes

2022-06-02 14:28 UTC, merged