CO : few changes
iptv-org/iptv pull request #7472
Opened 2022-06-08 16:11 UTC by LaneSh4d0w

Change Trece names to fit EPG
Add Canal 1 (mdstrm)

2022-06-08 16:31 UTC, its0x08 approved these changes, later dismissed

2022-06-12 18:07 UTC, what-a commented
For...
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/c/CanalCongresoColombia/live
I get...
"Could not get the link, Streamlink couldn't read https://www.youtube.com/c/CanalCongresoColombia/live"

2022-06-17 16:17 UTC, freearhey requested changes

2022-06-17 16:17 UTC, freearhey commented on streams/co.m3u
> +#EXTINF:-1 tvg-id="CanalCongreso.co" status="",Canal Congreso (Bogotà | Cundinamarca)
The YouTube stream is not available at the moment:

> Could not get the link, Streamlink couldn't read https://www.youtube.com/c/CanalCongresoColombia/live

```suggestion
#EXTINF:-1 tvg-id="CanalCongreso.co" status="",Canal Congreso (Bogotà | Cundinamarca) [Not 24/7]
```

2022-06-17 21:28 UTC, LaneSh4d0w commented
They indeed stream only if there's a meeting or a motion going on inside the Assembly.

2022-06-17 23:11 UTC, freearhey approved these changes

2022-06-18 23:10 UTC, what-a approved these changes

2022-06-19 07:29 UTC, merged