Change Cartoon Network (720p) to Cartoon Network (1080p)
iptv-org/iptv pull request #7502
Opened 2022-06-13 03:26 UTC by kirigizakazutovn

2022-06-13 17:16 UTC, BellezaEmporium requested changes
if the first link still works, why deleting it ? you can keep it as a secondary link.

to be put on vn_fptplay.m3u file.

adaptive is https://vips-livecdn.fptplay.net/hda3/cartoonnetworkhd_vhls.smil/playlist.m3u8

2022-06-17 16:10 UTC, freearhey commented on streams/us.m3u
> +https://vips-livecdn.fptplay.net/hda3/cartoonnetworkhd_vhls.smil/chunklist_b5000000.m3u8
<img width="756" alt="image" src="https://user-images.githubusercontent.com/7253922/174336188-0dee1304-9ad1-4f63-bd62-b9c2cf9ab9c6.png">

2022-06-17 16:10 UTC, closed without merging

2022-06-20 07:14 UTC, kirigizakazutovn commented
![Screenshot_2022-06-20-14-13-32-21](https://user-images.githubusercontent.com/83147867/174545523-7f1c3100-0c37-4106-8ebb-dc2755a3c361.png)
![Screenshot_2022-06-20-14-09-05-09](https://user-images.githubusercontent.com/83147867/174545567-462ad221-014c-4489-95b9-33dff3034beb.png)

2022-06-20 07:19 UTC, kirigizakazutovn commented
> 
The first link provided by HTVC through FPT Play But because HTVC has stopped cooperating with FPT Play, it doesn't work now There is a stream link hosted on Viettel's server 
[they are very strict about security, so can't get the link easily]

2022-06-20 07:28 UTC, kirigizakazutovn commented
In general, pay TV in Vietnam is also quite cheap About 3.79 USD for FPT Play MAX package
 For easier understanding: With a bowl of pho No. 10 Ly Quoc Su of Mr. Tan 1 Cu