Added Iraqi Channels, Logos, Updated Streams
iptv-org/iptv pull request #755
Opened 2019-12-01 22:05 UTC by themak1985

2019-12-02 00:38 UTC, freearhey requested changes

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="Al-Masar Al-Oula" tvg-language="Arabic" tvg-logo="https://i.imgur.com/npuXX8e.jpg" group-title="General",Al-Masar Al-Oula
tvg-name is wrong. It should be the same as the display-name from the EPG. If there is no such channel in the EPG, it is better to leave this attribute blank.

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +https://cllive.itworkscdn.net/alsumariatvlive/token=nva=1575257386~dirs=1~hash=0ca680b6400133ce1001b/sumariamob.smil/playlist.m3u8
New link does not work. Tested in VLC player and streamtest.in

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="Dijlah" tvg-language="Arabic" tvg-logo="https://www.dijlah.tv/templates/default-2/images/dlogo.png" group-title="General",Dijlah
tvg-name is wrong

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +#EXTINF:-1 tvg-id="" tvg-name="Dijlah" tvg-language="Arabic" tvg-logo="https://i.imgur.com/w5xVJZg.png" group-title="",Dijlah
tvg-name is wrong

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +http://116.203.71.169/hls/stream1.m3u8
tvg-name is wrong

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +https://k24mediaservice.streaming.mediaservices.windows.net/2d1065bf-4cde-4af3-a425-cef326a13e8c/6a9375c9-7438-4d88-8411-661f162c40d9.ism/manifest
tvg-name is wrong

2019-12-02 00:38 UTC, freearhey commented on channels/iq.m3u
> +http://116.203.41.89:8080/hls/stream.m3u8
tvg-name is wrong

2019-12-02 03:18 UTC, themak1985 commented
I think I messily fixed all the issues @freearhey  - sorry it took 3 commits.

2019-12-03 01:26 UTC, freearhey approved these changes

2019-12-03 01:26 UTC, merged

2019-12-03 01:28 UTC, freearhey commented
@themak1985 It's okay.