Update ph.m3u
iptv-org/iptv pull request #7553
Opened 2022-06-19 15:50 UTC by LouiseDenmar

Added GMA Network

2022-06-19 16:21 UTC, dct-infra approved these changes

2022-06-19 16:34 UTC, LaneSh4d0w commented
Xtream-Codes server, we do not allow these kind of links here.

2022-06-20 14:49 UTC, fotvnetwork commented
They stream select programs now on YouTube
https://www.youtube.com/c/gmanetwork

2022-06-20 20:25 UTC, MapGuy11 requested changes
Xtream Codes

2022-06-20 20:37 UTC, closed without merging