CW : Add Cariflix channels
iptv-org/iptv pull request #7647
Opened 2022-07-02 15:27 UTC by LaneSh4d0w

Contains channels from Bonaire (put in .bq), Aruba (not added here), and Curacao (this one)

2022-07-02 19:31 UTC, dct-infra reviewed
Issues from several locations.

2022-07-02 21:33 UTC, LaneSh4d0w commented
Some channels aren't 24/7 or lagging. Telecuracao for example has got the first Streann link working, but redirects automatically to the cachefly version. All those links actually go to their cachefly version. If it's dead then there's not much I can do.

2022-07-02 22:04 UTC, its0x08 submitted a review, later dismissed

2022-07-06 14:54 UTC, freearhey requested changes

2022-07-06 14:54 UTC, freearhey commented on streams/cw.m3u
> +https://d259pt51b9yens.cloudfront.net/out/v1/e471e39802f541a7ac923824af2e7269/playlist.m3u8
<img width="760" alt="image" src="https://user-images.githubusercontent.com/7253922/177579831-db622a5b-f6be-4cf1-9b7c-59a431877b9d.png">

2022-07-11 14:06 UTC, freearhey approved these changes

2022-07-13 21:44 UTC, its0x08 approved these changes

2022-07-15 17:11 UTC, what-a approved these changes

2022-07-15 18:39 UTC, merged