Update mw.m3u
iptv-org/iptv pull request #7847
Opened 2022-07-24 21:29 UTC by LaneSh4d0w

2022-07-24 23:03 UTC, its0x08 submitted a review, later dismissed

2022-07-25 00:02 UTC, freearhey approved these changes

2022-07-25 08:21 UTC, benevenstanciano commented
This should be Mauritius (.mv) rather than Malawi (.mw) right?

2022-07-25 12:47 UTC, freearhey requested changes
https://github.com/iptv-org/iptv/pull/7847#issuecomment-1193737336

2022-07-25 14:05 UTC, LaneSh4d0w commented
> This should be Maldives (.mv) rather than Malawi (.mw) right?

Indeed, the little difference fooled me.

2022-07-25 14:08 UTC, freearhey approved these changes

2022-07-28 15:51 UTC, what-a approved these changes

2022-07-28 16:10 UTC, merged