Update py.m3u
iptv-org/iptv pull request #7956
Opened 2022-08-05 02:14 UTC by fabiandv

update Senado TV and Somos Del Este

2022-08-05 03:05 UTC, sguinetti requested changes

2022-08-05 03:05 UTC, sguinetti commented on streams/py.m3u
> +https://59ce1298bfb98.streamlock.net/somosdeleste/somosdeleste/playlist.m3u8?PlaylistM3UCL
```suggestion
https://59ce1298bfb98.streamlock.net/somosdeleste/somosdeleste/playlist.m3u8
```

2022-08-10 22:48 UTC, LaneSh4d0w approved these changes

2022-08-11 22:30 UTC, sguinetti approved these changes

2022-08-12 21:04 UTC, merged