Update ar.m3u
iptv-org/iptv pull request #7968
Opened 2022-08-06 23:24 UTC by sguinetti

This PR add El Histonauta TV

2022-08-07 01:22 UTC, what-a approved these changes, later dismissed

2022-08-07 04:03 UTC, what-a approved these changes, later dismissed

2022-08-07 16:01 UTC, freearhey requested changes

2022-08-07 16:01 UTC, freearhey commented on streams/ar.m3u
> +#EXTINF:-1 tvg-id="Cadena103.ar" status="online",	Cadena 103
```suggestion
#EXTINF:-1 tvg-id="Cadena103.ar" status="online",Cadena 103
```

2022-08-07 18:31 UTC, freearhey approved these changes

2022-08-10 22:48 UTC, LaneSh4d0w approved these changes

2022-08-10 22:49 UTC, merged