Update bo.m3u
iptv-org/iptv pull request #7970
Opened 2022-08-07 01:31 UTC by sguinetti

This PR update streams from Bolivia.

2022-08-07 09:29 UTC, dct-infra reviewed
Ln 59, Please correct the space @sguinetti

2022-08-07 16:03 UTC, freearhey requested changes

2022-08-07 16:03 UTC, freearhey commented on streams/bo.m3u
> + https://solo.disfrutaenlared.com:1936/tuch/ngrp:tuch_all/playlist.m3u8
```suggestion
https://solo.disfrutaenlared.com:1936/tuch/ngrp:tuch_all/playlist.m3u8
```

2022-08-07 18:34 UTC, freearhey approved these changes

2022-08-10 22:37 UTC, LaneSh4d0w approved these changes

2022-08-10 22:38 UTC, merged