Update in.m3u
iptv-org/iptv pull request #8258
Opened 2022-08-25 16:10 UTC by freearhey

Closes #7670, closes #7849

2022-08-25 18:37 UTC, UltraHDR requested changes

2022-08-25 18:37 UTC, UltraHDR commented on streams/in.m3u
> +https://43wrzjnpqoxe-hls-live.wmncdn.net/indywood/indywoodtv/chunks.m3u8
```suggestion
https://43wrzjnpqoxe-hls-live.wmncdn.net/indywood/indywoodtv/index.m3u8
```

2022-08-25 18:37 UTC, UltraHDR approved these changes

2022-08-26 05:34 UTC, dct-infra approved these changes

2022-08-26 08:30 UTC, merged