Update kr.m3u
iptv-org/iptv pull request #9075
Opened 2022-09-26 15:31 UTC by Alstruit

Original Reference #9033:
Closed for a more clean history.

To implement:
Convert seeZN links to public links.
Append seeZN links 1080p by @freearhey scrapper tool.

2022-09-26 19:48 UTC, LaneSh4d0w commented
you'll need the channel number over Seezn's data.
285 is Mnet
273 is JTBC
213 is AsiaN

2022-09-28 01:19 UTC, Alstruit commented
Some channels from Seezn can be temporarly blocked at any time. Not sure if the 5 minute check is consistent.

2022-09-28 08:28 UTC, LaneSh4d0w commented
> Some channels from Seezn can be temporarly blocked at any time. Not sure if the 5 minute check is consistent.

I think i'll need to put my link inside the playlist to recreate a m3u file for each session. This would prevent the program cutting off unexpectedly.

2022-09-29 12:02 UTC, freearhey requested changes

2022-09-29 12:02 UTC, freearhey commented on streams/kr.m3u
> +https://www.youtube.com/channel/UCu6mog947IWOXL23AzKlImw/live
```suggestion
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCu6mog947IWOXL23AzKlImw/live
```

2022-09-29 12:02 UTC, freearhey commented on streams/kr.m3u
> +https://www.youtube.com/channel/UCnfwIKyFYRuqZzzKBDt6JOA/live
```suggestion
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.youtube.com/channel/UCnfwIKyFYRuqZzzKBDt6JOA/live
```

2022-09-29 16:21 UTC, LaneSh4d0w commented on streams/kr.m3u
> +#EXTINF:-1 tvg-id="JTBCGolfSports.kr" status="",JTBC Golf & Sports (480p) [Not 24/7] [Geo-locked]
```suggestion
#EXTINF:-1 tvg-id="JTBCGolfSports.kr" status="",JTBC Golf & Sports (480p) [Not 24/7] [Geo-blocked]
```

2022-09-30 06:55 UTC, freearhey approved these changes, later dismissed

2022-10-05 20:40 UTC, MapGuy11 approved these changes, later dismissed

2022-10-06 02:13 UTC, what-a submitted a review, later dismissed

2022-10-06 18:50 UTC, LaneSh4d0w approved these changes

2022-10-06 21:10 UTC, Red3amer reviewed
``

2022-10-07 00:12 UTC, what-a approved these changes

2022-10-07 03:07 UTC, merged