Update hu.m3u
iptv-org/iptv pull request #9520
Opened 2022-10-08 16:09 UTC by kristoft13

Added Zenebutik
Added Fix TV
Added Classics TV

2022-10-08 16:55 UTC, Alstruit requested changes
For adding Ids.

2022-10-08 16:55 UTC, Alstruit commented on streams/hu.m3u
> +#EXTINF:-1 tvg-id="" status="online",Fix TV (720p) [Not 24/7]
```suggestion
#EXTINF:-1 tvg-id="FixTV.hu" status="online",Fix TV (720p) [Not 24/7]
```

2022-10-08 16:55 UTC, Alstruit commented on streams/hu.m3u
> +#EXTINF:-1 tvg-id="" status="online",Zenebutik (720p) [Not 24/7]
```suggestion
#EXTINF:-1 tvg-id="Zenebutik.hu" status="online",Zenebutik (720p) [Not 24/7]
```

2022-10-08 20:18 UTC, LaneSh4d0w submitted a review, later dismissed

2022-10-08 20:19 UTC, LaneSh4d0w commented on streams/hu.m3u
> +https://s03.diazol.hu:7152/hls/live.m3u8
```suggestion
https://s03.diazol.hu:7152/live.m3u8
```
link above is simply a redirect to suggested link.

2022-10-08 22:15 UTC, Alstruit submitted a review, later dismissed

2022-10-08 22:16 UTC, Alstruit approved these changes

2022-10-09 03:24 UTC, what-a approved these changes

2022-10-09 06:08 UTC, merged